# DDC-CWICR-OE: DataDrivenConstruction · OpenConstructionERP
# Copyright (c) 2026 Artem Boiko / DataDrivenConstruction
"""File Transmittals (W7) service layer.

Holds the create/send lifecycle, the cover-sheet generator (PDF via
``reportlab`` when available, plain-text TXT fallback otherwise) and
the ack-token mint/verify flow used by the public ACK endpoint.
"""

from __future__ import annotations

import logging
import secrets
import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from fastapi import HTTPException, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.modules.file_transmittals.models import (
    TRANSMITTAL_REASONS,
    FileTransmittal,
    FileTransmittalItem,
    FileTransmittalRecipient,
)
from app.modules.file_transmittals.schemas import (
    TransmittalCreate,
    TransmittalItemCreate,
    TransmittalRecipientCreate,
)

if TYPE_CHECKING:  # pragma: no cover
    pass

logger = logging.getLogger(__name__)

_COVER_KEY_PREFIX = "transmittals"


# ── Cover-sheet generators ────────────────────────────────────────────────


def _build_cover_text(transmittal: FileTransmittal) -> bytes:
    """Compose a deterministic plain-text cover sheet for a transmittal.

    Used both as the TXT fallback when ``reportlab`` is unavailable and
    as the text source the PDF generator lays out. The format is human-
    readable and grep-friendly so a recipient can parse it manually if
    needed.
    """
    lines: list[str] = []
    lines.append("TRANSMITTAL COVER SHEET")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"Number:    {transmittal.number}")
    lines.append(f"Subject:   {transmittal.subject}")
    lines.append(f"Reason:    {transmittal.reason_code}")
    lines.append(f"Sent at:   {transmittal.sent_at.isoformat()}")
    lines.append(f"Status:    {transmittal.status}")
    if transmittal.notes:
        lines.append("")
        lines.append("Notes:")
        for nl in transmittal.notes.splitlines() or [transmittal.notes]:
            lines.append(f"  {nl}")
    lines.append("")
    lines.append("Items")
    lines.append("-" * 60)
    if not transmittal.items:
        lines.append("  (no items)")
    else:
        for idx, item in enumerate(transmittal.items, start=1):
            ver = (
                f" (v{item.file_version_snapshot})"
                if item.file_version_snapshot
                else ""
            )
            lines.append(
                f"  {idx:>2}. [{item.file_kind}] "
                f"{item.canonical_name_snapshot}{ver}"
            )
    lines.append("")
    lines.append("Recipients")
    lines.append("-" * 60)
    if not transmittal.recipients:
        lines.append("  (no recipients)")
    else:
        for r in transmittal.recipients:
            label = r.display_name or r.email
            role = f" — {r.role}" if r.role else ""
            lines.append(f"  - {label} <{r.email}>{role}")
    lines.append("")
    lines.append("=" * 60)
    lines.append(
        "Generated by OpenConstructionERP — File Transmittals (W7)."
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def _build_cover_pdf(transmittal: FileTransmittal) -> bytes | None:
    """Render a PDF cover sheet via ``reportlab``, or ``None`` if unavailable.

    The PDF is intentionally minimal: title, header table, body lines.
    Falls back to ``None`` (and the caller writes the plain-text version)
    on any failure so the send path never crashes on a layout error.
    """
    try:
        from io import BytesIO

        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
        from reportlab.lib import colors
    except Exception:  # noqa: BLE001 — optional dep
        logger.debug(
            "reportlab unavailable; transmittal cover will be TXT",
            exc_info=True,
        )
        return None

    try:
        buf = BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=LETTER,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            title=f"Transmittal {transmittal.number}",
            author="OpenConstructionERP",
        )
        styles = getSampleStyleSheet()
        story: list = []
        story.append(
            Paragraph(
                f"<b>Transmittal {transmittal.number}</b>",
                styles["Title"],
            )
        )
        story.append(Spacer(1, 0.15 * inch))

        header_rows = [
            ["Subject", transmittal.subject],
            ["Reason", transmittal.reason_code],
            ["Sent at", transmittal.sent_at.isoformat()],
            ["Status", transmittal.status],
        ]
        if transmittal.notes:
            header_rows.append(["Notes", transmittal.notes])
        tbl = Table(header_rows, colWidths=[1.2 * inch, 5.5 * inch])
        tbl.setStyle(
            TableStyle(
                [
                    ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
                    ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 9),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    (
                        "LINEBELOW",
                        (0, 0),
                        (-1, -1),
                        0.25,
                        colors.lightgrey,
                    ),
                ]
            )
        )
        story.append(tbl)
        story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph("<b>Items</b>", styles["Heading3"]))
        if not transmittal.items:
            story.append(Paragraph("<i>No items.</i>", styles["BodyText"]))
        else:
            data: list[list[str]] = [["#", "Kind", "Name", "Version"]]
            for idx, it in enumerate(transmittal.items, start=1):
                data.append(
                    [
                        str(idx),
                        it.file_kind,
                        it.canonical_name_snapshot,
                        it.file_version_snapshot or "",
                    ]
                )
            items_tbl = Table(
                data,
                colWidths=[0.4 * inch, 1.1 * inch, 4.7 * inch, 0.7 * inch],
            )
            items_tbl.setStyle(
                TableStyle(
                    [
                        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
                        ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
                        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                        (
                            "GRID",
                            (0, 0),
                            (-1, -1),
                            0.25,
                            colors.lightgrey,
                        ),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ]
                )
            )
            story.append(items_tbl)
        story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph("<b>Recipients</b>", styles["Heading3"]))
        if not transmittal.recipients:
            story.append(
                Paragraph("<i>No recipients.</i>", styles["BodyText"])
            )
        else:
            r_data: list[list[str]] = [["Email", "Name", "Role"]]
            for r in transmittal.recipients:
                r_data.append(
                    [r.email, r.display_name or "", r.role or ""]
                )
            r_tbl = Table(
                r_data,
                colWidths=[2.7 * inch, 2.2 * inch, 2.0 * inch],
            )
            r_tbl.setStyle(
                TableStyle(
                    [
                        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
                        ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
                        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                        (
                            "GRID",
                            (0, 0),
                            (-1, -1),
                            0.25,
                            colors.lightgrey,
                        ),
                    ]
                )
            )
            story.append(r_tbl)
        doc.build(story)
        return buf.getvalue()
    except Exception:  # noqa: BLE001 — never let cover-render crash the send
        logger.exception(
            "Cover-sheet PDF generation failed; falling back to TXT"
        )
        return None


# ── Service ───────────────────────────────────────────────────────────────


class TransmittalService:
    """Stateless business logic for ``oe_file_transmittal``."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    # ── Read ───────────────────────────────────────────────────────────

    async def list_for_project(
        self, project_id: uuid.UUID
    ) -> list[FileTransmittal]:
        """Newest-first transmittal list for a project."""
        stmt = (
            select(FileTransmittal)
            .where(FileTransmittal.project_id == project_id)
            .options(
                selectinload(FileTransmittal.items),
                selectinload(FileTransmittal.recipients),
            )
            .order_by(FileTransmittal.created_at.desc())
        )
        return list((await self.session.execute(stmt)).scalars().all())

    async def get(self, transmittal_id: uuid.UUID) -> FileTransmittal:
        """Load by id (404 on miss). Items + recipients eagerly loaded."""
        stmt = (
            select(FileTransmittal)
            .where(FileTransmittal.id == transmittal_id)
            .options(
                selectinload(FileTransmittal.items),
                selectinload(FileTransmittal.recipients),
            )
        )
        row = (await self.session.execute(stmt)).scalar_one_or_none()
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Transmittal {transmittal_id} not found",
            )
        return row

    # ── Number allocation ─────────────────────────────────────────────

    async def _next_number(self, project_id: uuid.UUID) -> str:
        """Allocate ``T-NNNN`` based on ``MAX(number)`` for the project.

        ``UniqueConstraint(project_id, number)`` is the final guard
        against a race; the service-level allocation is the optimistic
        path.
        """
        stmt = select(func.count(FileTransmittal.id)).where(
            FileTransmittal.project_id == project_id
        )
        current = int((await self.session.execute(stmt)).scalar_one() or 0)
        # Parse existing numbers to find the actual max (skips manual edits).
        max_stmt = select(FileTransmittal.number).where(
            FileTransmittal.project_id == project_id
        )
        max_n = 0
        for (num,) in (await self.session.execute(max_stmt)).all():
            try:
                n = int(str(num).removeprefix("T-").lstrip("0") or "0")
                if n > max_n:
                    max_n = n
            except ValueError:
                continue
        return f"T-{max(max_n, current) + 1:04d}"

    # ── Create / mutate ───────────────────────────────────────────────

    async def create_draft(
        self,
        data: TransmittalCreate,
        sender_id: str | None,
    ) -> FileTransmittal:
        """Create a draft transmittal with optional items + recipients.

        ``sent_at`` is initialised to ``utcnow()`` so the row is sortable
        immediately; the ``send/`` endpoint refreshes it to the actual
        send timestamp when the draft is dispatched.
        """
        if data.reason_code not in TRANSMITTAL_REASONS:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Unknown reason_code '{data.reason_code}'",
            )
        number = await self._next_number(data.project_id)
        now = datetime.now(UTC)
        sender_uuid: uuid.UUID | None = None
        if sender_id:
            try:
                sender_uuid = uuid.UUID(str(sender_id))
            except (TypeError, ValueError):
                sender_uuid = None
        transmittal = FileTransmittal(
            project_id=data.project_id,
            number=number,
            subject=data.subject,
            reason_code=data.reason_code,
            sender_id=sender_uuid,
            sent_at=now,
            status="draft",
            notes=data.notes,
        )
        self.session.add(transmittal)
        await self.session.flush()

        for idx, it in enumerate(data.items):
            self.session.add(
                FileTransmittalItem(
                    transmittal_id=transmittal.id,
                    file_kind=it.file_kind,
                    file_id=it.file_id,
                    canonical_name_snapshot=it.canonical_name_snapshot,
                    file_version_snapshot=it.file_version_snapshot,
                    sort_order=it.sort_order or idx,
                )
            )
        for r in data.recipients:
            self.session.add(
                FileTransmittalRecipient(
                    transmittal_id=transmittal.id,
                    email=str(r.email).lower(),
                    display_name=r.display_name,
                    role=r.role,
                )
            )
        await self.session.flush()
        return await self.get(transmittal.id)

    async def add_item(
        self, transmittal_id: uuid.UUID, item: TransmittalItemCreate
    ) -> FileTransmittalItem:
        """Append an item to an existing transmittal."""
        transmittal = await self.get(transmittal_id)
        # Compute next sort order.
        next_order = (
            max((it.sort_order for it in transmittal.items), default=-1) + 1
        )
        row = FileTransmittalItem(
            transmittal_id=transmittal.id,
            file_kind=item.file_kind,
            file_id=item.file_id,
            canonical_name_snapshot=item.canonical_name_snapshot,
            file_version_snapshot=item.file_version_snapshot,
            sort_order=item.sort_order or next_order,
        )
        self.session.add(row)
        await self.session.flush()
        return row

    async def remove_item(
        self, transmittal_id: uuid.UUID, item_id: uuid.UUID
    ) -> None:
        """Delete one item from a transmittal."""
        stmt = select(FileTransmittalItem).where(
            FileTransmittalItem.id == item_id,
            FileTransmittalItem.transmittal_id == transmittal_id,
        )
        row = (await self.session.execute(stmt)).scalar_one_or_none()
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Item {item_id} not found in transmittal "
                f"{transmittal_id}",
            )
        await self.session.delete(row)
        await self.session.flush()
        # Expire the parent transmittal's relationship cache so a
        # subsequent ``get()`` reflects the deletion. Without this the
        # SQLAlchemy identity-map keeps the stale items collection.
        parent = await self.session.get(FileTransmittal, transmittal_id)
        if parent is not None:
            await self.session.refresh(parent, ["items"])

    async def add_recipient(
        self,
        transmittal_id: uuid.UUID,
        recipient: TransmittalRecipientCreate,
    ) -> FileTransmittalRecipient:
        """Append a recipient to an existing transmittal (idempotent on email)."""
        transmittal = await self.get(transmittal_id)
        email_lower = str(recipient.email).lower()
        for existing in transmittal.recipients:
            if existing.email.lower() == email_lower:
                return existing
        row = FileTransmittalRecipient(
            transmittal_id=transmittal.id,
            email=email_lower,
            display_name=recipient.display_name,
            role=recipient.role,
        )
        self.session.add(row)
        await self.session.flush()
        return row

    # ── Send (mint tokens + generate cover) ───────────────────────────

    async def send(
        self,
        transmittal_id: uuid.UUID,
    ) -> FileTransmittal:
        """Flip status → sent, mint ack tokens, generate cover sheet.

        Idempotent: calling on an already-sent transmittal returns the
        existing row without re-minting tokens.
        """
        from app.core.storage import get_storage_backend

        transmittal = await self.get(transmittal_id)
        if transmittal.status != "draft":
            return transmittal

        now = datetime.now(UTC)
        transmittal.sent_at = now
        transmittal.status = "sent"

        # Mint single-use ack tokens for every recipient that doesn't
        # already have one.
        for r in transmittal.recipients:
            if not r.acknowledge_token:
                r.acknowledge_token = secrets.token_urlsafe(32)[:64]

        await self.session.flush()
        # Re-load with items + recipients to make the cover sheet.
        transmittal = await self.get(transmittal.id)

        # Generate cover sheet (PDF preferred, TXT fallback).
        pdf_bytes = _build_cover_pdf(transmittal)
        if pdf_bytes is not None:
            cover_bytes = pdf_bytes
            ext = "pdf"
        else:
            cover_bytes = _build_cover_text(transmittal)
            ext = "txt"
        key = (
            f"{_COVER_KEY_PREFIX}/{transmittal.project_id}/"
            f"{transmittal.id}/cover.{ext}"
        )
        try:
            await get_storage_backend().put(key, cover_bytes)
            transmittal.cover_sheet_path = key
        except Exception:  # noqa: BLE001 — never let storage crash the send
            logger.exception(
                "Failed to persist transmittal cover sheet to storage"
            )
            transmittal.cover_sheet_path = None
        await self.session.flush()
        return transmittal

    # ── Acknowledge (public) ──────────────────────────────────────────

    async def acknowledge_by_token(
        self, token: str
    ) -> tuple[FileTransmittal, FileTransmittalRecipient]:
        """Mark the recipient identified by ``token`` as acknowledged."""
        if not token:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Invalid acknowledgement token",
            )
        stmt = select(FileTransmittalRecipient).where(
            FileTransmittalRecipient.acknowledge_token == token
        )
        recipient = (
            await self.session.execute(stmt)
        ).scalar_one_or_none()
        if recipient is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Invalid acknowledgement token",
            )
        if recipient.acknowledged_at is None:
            recipient.acknowledged_at = datetime.now(UTC)
            await self.session.flush()
        # Promote the transmittal as a whole to acknowledged when every
        # recipient has acked.
        transmittal = await self.get(recipient.transmittal_id)
        if all(
            r.acknowledged_at is not None for r in transmittal.recipients
        ):
            transmittal.status = "acknowledged"
            await self.session.flush()
        return transmittal, recipient

    # ── Cover read ────────────────────────────────────────────────────

    async def read_cover(self, transmittal_id: uuid.UUID) -> tuple[bytes, str]:
        """Return ``(bytes, media_type)`` for the cover sheet, regenerating
        the bytes on the fly when storage is unavailable so the endpoint
        never 500s after a storage hiccup.
        """
        from app.core.storage import get_storage_backend

        transmittal = await self.get(transmittal_id)
        if transmittal.cover_sheet_path:
            try:
                data = await get_storage_backend().get(
                    transmittal.cover_sheet_path
                )
                if transmittal.cover_sheet_path.endswith(".pdf"):
                    return data, "application/pdf"
                return data, "text/plain; charset=utf-8"
            except Exception:  # noqa: BLE001
                logger.exception(
                    "Storage read failed for transmittal %s; regenerating",
                    transmittal_id,
                )
        # Fall back to live regeneration.
        pdf = _build_cover_pdf(transmittal)
        if pdf is not None:
            return pdf, "application/pdf"
        return _build_cover_text(transmittal), "text/plain; charset=utf-8"
