"""AI Estimation Pydantic schemas — request/response models.

Defines schemas for AI settings management, quick/photo estimate requests,
and estimate job responses with generated BOQ items.
"""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# ── AI Settings schemas ──────────────────────────────────────────────────────


class AISettingsUpdate(BaseModel):
    """Update per-user AI configuration (API keys, preferred model)."""

    model_config = ConfigDict(str_strip_whitespace=True)

    anthropic_api_key: str | None = None
    openai_api_key: str | None = None
    gemini_api_key: str | None = None
    openrouter_api_key: str | None = None
    mistral_api_key: str | None = None
    groq_api_key: str | None = None
    deepseek_api_key: str | None = None
    together_api_key: str | None = None
    fireworks_api_key: str | None = None
    perplexity_api_key: str | None = None
    cohere_api_key: str | None = None
    ai21_api_key: str | None = None
    xai_api_key: str | None = None
    zhipu_api_key: str | None = None
    baidu_api_key: str | None = None
    yandex_api_key: str | None = None
    gigachat_api_key: str | None = None
    preferred_model: str | None = Field(default=None, max_length=100)


class AISettingsResponse(BaseModel):
    """AI settings returned from the API.

    API keys are masked — only the last 4 characters are shown.
    """

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id: UUID
    user_id: UUID
    anthropic_api_key_set: bool = False
    openai_api_key_set: bool = False
    gemini_api_key_set: bool = False
    openrouter_api_key_set: bool = False
    mistral_api_key_set: bool = False
    groq_api_key_set: bool = False
    deepseek_api_key_set: bool = False
    together_api_key_set: bool = False
    fireworks_api_key_set: bool = False
    perplexity_api_key_set: bool = False
    cohere_api_key_set: bool = False
    ai21_api_key_set: bool = False
    xai_api_key_set: bool = False
    zhipu_api_key_set: bool = False
    baidu_api_key_set: bool = False
    yandex_api_key_set: bool = False
    gigachat_api_key_set: bool = False
    preferred_model: str
    metadata: dict[str, Any] = Field(default_factory=dict, alias="metadata_")
    created_at: datetime
    updated_at: datetime


# ── Estimate request schemas ─────────────────────────────────────────────────


class QuickEstimateRequest(BaseModel):
    """Text-based quick estimation request.

    The AI analyses the description and generates a full BOQ.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    description: str = Field(..., min_length=10, max_length=5000, description="Project description")
    project_type: str | None = Field(
        default=None,
        max_length=100,
        description="Building type: office, residential, warehouse, etc.",
    )
    area_m2: float | None = Field(default=None, gt=0, le=1_000_000, description="Total area in m2")
    location: str | None = Field(default=None, max_length=200, description="City or country for pricing context")
    currency: str | None = Field(default=None, max_length=10, description="Currency code: EUR, USD, GBP, etc.")
    standard: str | None = Field(
        default=None,
        max_length=50,
        description="Classification standard: din276, nrm, masterformat",
    )
    project_id: UUID | None = Field(default=None, description="Optional project to link the estimate job to")


class PhotoEstimateRequest(BaseModel):
    """Photo-based estimation request metadata.

    The photo file is uploaded separately via multipart form data.
    This schema captures the additional context fields.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    location: str | None = Field(default=None, max_length=200)
    currency: str | None = Field(default=None, max_length=10)
    standard: str | None = Field(default=None, max_length=50)
    project_id: UUID | None = None


# ── Estimate result schemas ──────────────────────────────────────────────────


class EstimateItem(BaseModel):
    """A single work item generated by AI estimation."""

    ordinal: str = ""
    description: str
    unit: str = "m2"
    quantity: float = 0.0
    unit_rate: float = 0.0
    total: float = 0.0
    classification: dict[str, str] = Field(default_factory=dict)
    category: str = "General"
    confidence: float | None = None


class EstimateJobResponse(BaseModel):
    """Full AI estimation job response — status, items, and metadata."""

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)

    id: UUID
    user_id: UUID
    project_id: UUID | None = None
    input_type: str
    input_text: str | None = None
    input_filename: str | None = None
    status: str
    items: list[EstimateItem] = Field(default_factory=list)
    error_message: str | None = None
    model_used: str | None = None
    tokens_used: int = 0
    duration_ms: int = 0
    grand_total: float = 0.0
    created_at: datetime
    updated_at: datetime


class CreateBOQFromEstimateRequest(BaseModel):
    """Request to create a real BOQ from an AI estimate job."""

    model_config = ConfigDict(str_strip_whitespace=True)

    project_id: UUID
    boq_name: str = Field(default="AI Estimate", min_length=1, max_length=255)
