from __future__ import annotations

from app.core.demo_projects import DemoTemplate

# ---------------------------------------------------------------------------
# Flagship demo pack: India / CPWD — Government Institutional Building, New Delhi
# ---------------------------------------------------------------------------
# Costing follows the CPWD Delhi Schedule of Rates (DSR) 2021 sub-head
# structure with Delhi 2026 market rates. Item references carry CPWD DSR
# clause numbers in the classification dict (key "cpwd"); a MasterFormat
# division is supplied as the platform fallback standard. Rates are GST-
# exclusive (GST 18% is carried as a separate markup line). Design intent
# conforms to IS 456 (RCC), IS 1893:2016 (seismic — Zone IV), IS 13920
# (ductile detailing), IS 875 (loads), IS 800 (structural steel),
# NBC 2016 and the relevant CPWD General Specifications.
# ---------------------------------------------------------------------------

TEMPLATE = DemoTemplate(
    demo_id="govt-building-delhi",
    project_name="Government Office Complex — New Delhi (CPWD)",
    project_description=(
        "Construction of a G+5 reinforced-concrete government office and "
        "administrative block for a Central Ministry at Lodhi Road, New Delhi. "
        "Gross floor area approx. 7,800 m2 over six storeys plus one basement "
        "for parking and services; built-up plot approx. 2,400 m2. RCC special "
        "moment-resisting framed structure (SMRF) designed to IS 456 and "
        "IS 1893:2016 for Seismic Zone IV (importance factor 1.5, response "
        "reduction R=5), with ductile detailing to IS 13920. GRIHA 4-star / "
        "ECBC-compliant envelope, double-glazed unitised facade, fly-ash "
        "brick infill. Executed on CPWD DSR 2021 rates at Delhi 2026 price "
        "level. Headline construction cost approx. INR 38 crore (380 million)."
    ),
    region="IN",
    classification_standard="masterformat",
    currency="INR",
    locale="en",
    address={
        "street": "Lodhi Road, CGO Complex",
        "city": "New Delhi",
        "postcode": "110003",
        "country": "India",
        "lat": 28.5921,
        "lng": 77.2290,
    },
    validation_rule_sets=["masterformat", "boq_quality", "project_completeness"],
    boq_name="Bill of Quantities — CPWD DSR 2021 (Civil & Services)",
    boq_description=(
        "Detailed BoQ prepared on CPWD Delhi Schedule of Rates 2021, "
        "all sub-heads from Earthwork to External Services. Quantities to "
        "IS 1200 mode of measurement; rates GST-exclusive."
    ),
    boq_metadata={
        "standard": "CPWD DSR 2021 (Delhi)",
        "phase": "Detailed Estimate / Tender BoQ",
        "base_date": "2026-Q1",
        "price_level": "Delhi 2026",
    },
    sections=[
        # ── 1. Earthwork / Site Clearance (CPWD Sub-head 1) ───────────
        (
            "1",
            "Earthwork & Site Preparation",
            {"masterformat": "31 00 00", "cpwd": "DSR-1"},
            [
                (
                    "1.1",
                    "Site clearance, dismantling & removal of existing structures (sthal saphai)",
                    "m2",
                    2400,
                    65.00,
                    {"masterformat": "31 11 00", "cpwd": "1.1"},
                ),
                (
                    "1.2",
                    "Earthwork in excavation in foundation, all kinds of soil, up to 1.5 m depth",
                    "m3",
                    9600,
                    285.00,
                    {"masterformat": "31 23 16", "cpwd": "2.6"},
                ),
                (
                    "1.3",
                    "Extra for excavation exceeding 1.5 m and up to 3.0 m depth (basement)",
                    "m3",
                    4200,
                    95.00,
                    {"masterformat": "31 23 16", "cpwd": "2.7"},
                ),
                (
                    "1.4",
                    "Disposal of surplus excavated earth, lead up to 5 km (mitti hatana)",
                    "m3",
                    8200,
                    245.00,
                    {"masterformat": "31 23 23", "cpwd": "2.31"},
                ),
                (
                    "1.5",
                    "Filling in foundation / plinth with selected earth in 20 cm layers, watered & rammed",
                    "m3",
                    3600,
                    215.00,
                    {"masterformat": "31 23 23", "cpwd": "2.25"},
                ),
                (
                    "1.6",
                    "Sand filling under floors, consolidated 15 cm thick (balu bharai)",
                    "m3",
                    480,
                    1850.00,
                    {"masterformat": "31 23 23", "cpwd": "2.27"},
                ),
                (
                    "1.7",
                    "Anti-termite soil treatment, pre-construction, conforming to IS 6313",
                    "m2",
                    2400,
                    78.00,
                    {"masterformat": "31 31 16", "cpwd": "8.1"},
                ),
                (
                    "1.8",
                    "Dewatering of foundation pits during construction (paani nikasi)",
                    "lsum",
                    1,
                    650000.00,
                    {"masterformat": "31 23 19", "cpwd": "2.9"},
                ),
                (
                    "1.9",
                    "Geotechnical investigation, boreholes & SBC report (mitti jaanch)",
                    "lsum",
                    1,
                    420000.00,
                    {"masterformat": "31 00 00", "cpwd": "2.1"},
                ),
            ],
        ),
        # ── 2. Concrete Work / RCC (CPWD Sub-head 4 & 5) ──────────────
        (
            "2",
            "Concrete Work & RCC",
            {"masterformat": "03 00 00", "cpwd": "DSR-4"},
            [
                (
                    "2.1",
                    "Providing & laying PCC 1:4:8 in foundation & under floors (lean concrete)",
                    "m3",
                    310,
                    6850.00,
                    {"masterformat": "03 30 00", "cpwd": "4.1.4"},
                ),
                (
                    "2.2",
                    "RCC M30 design mix in raft & footings, incl. centering/shuttering, IS 456",
                    "m3",
                    980,
                    9650.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.2"},
                ),
                (
                    "2.3",
                    "RCC M30 in columns & shear walls, incl. shuttering, IS 13920 ductile detail",
                    "m3",
                    620,
                    11250.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.3"},
                ),
                (
                    "2.4",
                    "RCC M30 in beams, incl. centering & shuttering (sariya & shuttering)",
                    "m3",
                    740,
                    10850.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.4"},
                ),
                (
                    "2.5",
                    "RCC M30 in suspended slabs up to 4.5 m height, incl. shuttering",
                    "m3",
                    1180,
                    10250.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.5"},
                ),
                (
                    "2.6",
                    "RCC M25 in staircases incl. landings, risers & shuttering (seedhi)",
                    "m3",
                    95,
                    11850.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.7"},
                ),
                (
                    "2.7",
                    "TMT reinforcement bars Fe 500D, cut bent & placed in position, IS 1786",
                    "t",
                    485,
                    78500.00,
                    {"masterformat": "03 21 00", "cpwd": "5.22.6"},
                ),
                (
                    "2.8",
                    "Extra for M40 design-mix concrete in basement retaining walls (water-tight)",
                    "m3",
                    280,
                    1850.00,
                    {"masterformat": "03 30 00", "cpwd": "5.9.6"},
                ),
                (
                    "2.9",
                    "Water-proofing compound integral, dosed in RCC (water-proofing yaugik)",
                    "kg",
                    12500,
                    42.00,
                    {"masterformat": "07 16 00", "cpwd": "5.3"},
                ),
                (
                    "2.10",
                    "RCC precast cover slabs / chajja & sunshades incl. reinforcement",
                    "m2",
                    640,
                    1450.00,
                    {"masterformat": "03 41 00", "cpwd": "5.11"},
                ),
            ],
        ),
        # ── 3. Brick / Masonry Work (CPWD Sub-head 6) ─────────────────
        (
            "3",
            "Brick & Block Masonry",
            {"masterformat": "04 00 00", "cpwd": "DSR-6"},
            [
                (
                    "3.1",
                    "Brickwork in fly-ash bricks class 7.5 in CM 1:6, superstructure (chinai)",
                    "m3",
                    1850,
                    7250.00,
                    {"masterformat": "04 21 13", "cpwd": "6.1.2"},
                ),
                (
                    "3.2",
                    "Half-brick (115 mm) partition wall in CM 1:4 with 6 mm bars at every 3rd course",
                    "m2",
                    3200,
                    985.00,
                    {"masterformat": "04 21 13", "cpwd": "6.13.2"},
                ),
                (
                    "3.3",
                    "AAC block masonry 200 mm in external walls, polymer mortar (halka block)",
                    "m3",
                    920,
                    6450.00,
                    {"masterformat": "04 22 00", "cpwd": "6.4"},
                ),
                (
                    "3.4",
                    "RCC band / lintel band at sill & lintel level for seismic safety (IS 4326)",
                    "m",
                    1850,
                    485.00,
                    {"masterformat": "04 05 23", "cpwd": "6.30"},
                ),
                (
                    "3.5",
                    "Damp-proof course 50 mm CC 1:2:4 with water-proofing at plinth (DPC)",
                    "m2",
                    480,
                    685.00,
                    {"masterformat": "07 16 00", "cpwd": "4.2"},
                ),
                (
                    "3.6",
                    "Stone / granite cladding 18 mm on external wall, mechanically fixed",
                    "m2",
                    420,
                    4850.00,
                    {"masterformat": "04 42 00", "cpwd": "8.18"},
                ),
            ],
        ),
        # ── 4. Wood, PVC & Joinery Work (CPWD Sub-head 9) ─────────────
        (
            "4",
            "Wood, PVC & Joinery Work",
            {"masterformat": "08 00 00", "cpwd": "DSR-9"},
            [
                (
                    "4.1",
                    "Flush door shutters 35 mm, BWP grade, with hardwood frame & fittings (darwaza)",
                    "m2",
                    560,
                    4250.00,
                    {"masterformat": "08 14 00", "cpwd": "9.21"},
                ),
                (
                    "4.2",
                    "Factory-made WPC door frame & shutter for toilets, complete (PVC darwaza)",
                    "each",
                    96,
                    6850.00,
                    {"masterformat": "08 14 00", "cpwd": "9.122"},
                ),
                (
                    "4.3",
                    "Fire-rated steel door 2 hr rating with vision panel & panic bar, IS 3614",
                    "each",
                    28,
                    38500.00,
                    {"masterformat": "08 16 13", "cpwd": "9.95"},
                ),
                (
                    "4.4",
                    "Hardware set per door — mortise lock, hinges, handles, door closer (chitkani)",
                    "each",
                    420,
                    3850.00,
                    {"masterformat": "08 71 00", "cpwd": "9.100"},
                ),
                (
                    "4.5",
                    "Modular gypsum / laminate partition for office cabins, 100 mm (vibhajan)",
                    "m2",
                    1850,
                    2650.00,
                    {"masterformat": "10 22 00", "cpwd": "9.180"},
                ),
                (
                    "4.6",
                    "Aluminium-framed glazed cabin doors with float glass 12 mm (kaanch darwaza)",
                    "each",
                    62,
                    18500.00,
                    {"masterformat": "08 41 00", "cpwd": "9.190"},
                ),
            ],
        ),
        # ── 5. Steel & Aluminium Work (CPWD Sub-head 10) ──────────────
        (
            "5",
            "Steel & Aluminium Work",
            {"masterformat": "05 00 00", "cpwd": "DSR-10"},
            [
                (
                    "5.1",
                    "Structural steel in trusses / canopy, fabricated & erected, IS 800 (loha kaam)",
                    "t",
                    42,
                    118500.00,
                    {"masterformat": "05 12 00", "cpwd": "10.1"},
                ),
                (
                    "5.2",
                    "MS railing / balustrade in staircase, fabricated to drawing (jangla)",
                    "m",
                    480,
                    2850.00,
                    {"masterformat": "05 52 00", "cpwd": "10.25"},
                ),
                (
                    "5.3",
                    "Stainless-steel handrail SS 304 with glass infill for lobby & atrium",
                    "m",
                    220,
                    6850.00,
                    {"masterformat": "05 52 13", "cpwd": "10.27"},
                ),
                (
                    "5.4",
                    "MS grille / window security bars, fabricated & fixed (loha jaali)",
                    "kg",
                    8600,
                    145.00,
                    {"masterformat": "05 50 00", "cpwd": "10.15"},
                ),
                (
                    "5.5",
                    "Rolling shutter MS for store / service entries, manual operation (shutter)",
                    "m2",
                    180,
                    3650.00,
                    {"masterformat": "08 33 00", "cpwd": "10.28"},
                ),
                (
                    "5.6",
                    "Galvanised steel chequered plate cover for drains & ducts, IS 3502",
                    "m2",
                    120,
                    4250.00,
                    {"masterformat": "05 53 00", "cpwd": "10.20"},
                ),
            ],
        ),
        # ── 6. Flooring & Tiling (CPWD Sub-head 11) ───────────────────
        (
            "6",
            "Flooring & Tiling",
            {"masterformat": "09 60 00", "cpwd": "DSR-11"},
            [
                (
                    "6.1",
                    "Vitrified tile flooring 800x800 mm, premium, on CM bed (farsh tiles)",
                    "m2",
                    4200,
                    1650.00,
                    {"masterformat": "09 30 13", "cpwd": "11.42"},
                ),
                (
                    "6.2",
                    "Polished Kota / granite stone flooring 18 mm in lobbies & corridors",
                    "m2",
                    1450,
                    2850.00,
                    {"masterformat": "09 63 40", "cpwd": "11.21"},
                ),
                (
                    "6.3",
                    "Ceramic anti-skid tile flooring in toilets & wet areas 300x300 mm",
                    "m2",
                    980,
                    1150.00,
                    {"masterformat": "09 30 13", "cpwd": "11.38"},
                ),
                (
                    "6.4",
                    "Glazed ceramic wall tiling dado 300x600 mm in toilets up to 2.1 m height",
                    "m2",
                    1850,
                    1350.00,
                    {"masterformat": "09 30 13", "cpwd": "11.45"},
                ),
                (
                    "6.5",
                    "Cement concrete 1:2:4 flooring 40 mm in basement & service areas",
                    "m2",
                    2400,
                    685.00,
                    {"masterformat": "03 35 00", "cpwd": "11.3"},
                ),
                (
                    "6.6",
                    "Skirting 100 mm high in matching vitrified / stone (jhalar)",
                    "m",
                    2600,
                    285.00,
                    {"masterformat": "09 30 13", "cpwd": "11.50"},
                ),
                (
                    "6.7",
                    "Epoxy floor coating in plant rooms & laboratories, 3 mm self-levelling",
                    "m2",
                    480,
                    1450.00,
                    {"masterformat": "09 67 00", "cpwd": "11.60"},
                ),
                (
                    "6.8",
                    "Raised access flooring 600x600 mm steel panels in server / IT rooms",
                    "m2",
                    220,
                    3850.00,
                    {"masterformat": "09 69 00", "cpwd": "11.62"},
                ),
            ],
        ),
        # ── 7. Finishing — Plaster, Paint, Ceiling (CPWD Sub-head 13) ─
        (
            "7",
            "Finishing — Plaster, Paint & Ceiling",
            {"masterformat": "09 90 00", "cpwd": "DSR-13"},
            [
                (
                    "7.1",
                    "Cement plaster 12 mm in CM 1:4 on internal walls (andar plaster)",
                    "m2",
                    18500,
                    265.00,
                    {"masterformat": "09 24 00", "cpwd": "13.1"},
                ),
                (
                    "7.2",
                    "Cement plaster 20 mm two-coat on external walls, sponge finish (bahar plaster)",
                    "m2",
                    6200,
                    385.00,
                    {"masterformat": "09 24 00", "cpwd": "13.5"},
                ),
                (
                    "7.3",
                    "Acrylic emulsion paint two coats on primed internal walls & ceiling (rang)",
                    "m2",
                    24700,
                    115.00,
                    {"masterformat": "09 91 23", "cpwd": "13.61"},
                ),
                (
                    "7.4",
                    "Exterior weatherproof acrylic paint (Apex) two coats over primer",
                    "m2",
                    6200,
                    185.00,
                    {"masterformat": "09 91 13", "cpwd": "13.80"},
                ),
                (
                    "7.5",
                    "Gypsum board false ceiling on GI framing, taped & jointed (chhat)",
                    "m2",
                    4800,
                    985.00,
                    {"masterformat": "09 51 00", "cpwd": "13.91"},
                ),
                (
                    "7.6",
                    "Mineral-fibre acoustic tile ceiling 600x600 mm in offices & halls",
                    "m2",
                    2200,
                    1150.00,
                    {"masterformat": "09 51 13", "cpwd": "13.93"},
                ),
                (
                    "7.7",
                    "Synthetic enamel paint on steel & joinery, two coats over primer",
                    "m2",
                    3600,
                    145.00,
                    {"masterformat": "09 91 00", "cpwd": "13.50"},
                ),
                (
                    "7.8",
                    "Texture / putty base preparation on plastered surfaces before paint",
                    "m2",
                    24700,
                    65.00,
                    {"masterformat": "09 91 00", "cpwd": "13.40"},
                ),
            ],
        ),
        # ── 8. Water Supply & Sanitary (CPWD Sub-head 17 & 18) ────────
        (
            "8",
            "Water Supply & Sanitary Installation",
            {"masterformat": "22 00 00", "cpwd": "DSR-17"},
            [
                (
                    "8.1",
                    "CPVC water-supply piping 25-50 mm, concealed, with fittings (paani ki line)",
                    "m",
                    4800,
                    385.00,
                    {"masterformat": "22 11 00", "cpwd": "18.12"},
                ),
                (
                    "8.2",
                    "PVC-U soil & waste piping 110 mm, SWR system, with fittings (nikasi)",
                    "m",
                    3200,
                    485.00,
                    {"masterformat": "22 13 00", "cpwd": "17.5"},
                ),
                (
                    "8.3",
                    "European water-closet vitreous china with concealed cistern (shauchalay)",
                    "each",
                    96,
                    8650.00,
                    {"masterformat": "22 41 00", "cpwd": "17.10"},
                ),
                (
                    "8.4",
                    "Wash-basin vitreous china with CP fittings & waste (washbasin)",
                    "each",
                    78,
                    4850.00,
                    {"masterformat": "22 41 00", "cpwd": "17.20"},
                ),
                (
                    "8.5",
                    "Stainless-steel kitchen / pantry sink with drain board & CP taps",
                    "each",
                    18,
                    7850.00,
                    {"masterformat": "22 41 00", "cpwd": "17.35"},
                ),
                (
                    "8.6",
                    "RCC underground water tank 150 kL, water-proofed (paani ki tanki)",
                    "lsum",
                    1,
                    1850000.00,
                    {"masterformat": "22 12 00", "cpwd": "17.50"},
                ),
                (
                    "8.7",
                    "Hydro-pneumatic pump set 2x15 HP with pressure vessel & controls",
                    "lsum",
                    1,
                    1250000.00,
                    {"masterformat": "22 11 23", "cpwd": "18.40"},
                ),
                (
                    "8.8",
                    "Sewage treatment plant 80 KLD packaged (MBBR) with disposal (STP)",
                    "lsum",
                    1,
                    4500000.00,
                    {"masterformat": "22 13 00", "cpwd": "18.60"},
                ),
                (
                    "8.9",
                    "Rainwater harvesting recharge pits & storm-water network, CGWB norms",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "33 40 00", "cpwd": "18.70"},
                ),
            ],
        ),
        # ── 9. Electrical Installation (CPWD Electrical DSR) ──────────
        (
            "9",
            "Electrical Installation",
            {"masterformat": "26 00 00", "cpwd": "DSR-ELEC"},
            [
                (
                    "9.1",
                    "11kV/433V package substation 1000 kVA with transformer & RMU (bijli ghar)",
                    "lsum",
                    1,
                    6850000.00,
                    {"masterformat": "26 11 00", "cpwd": "E-1.1"},
                ),
                (
                    "9.2",
                    "DG set 500 kVA acoustic enclosure with AMF panel & fuel tank (generator)",
                    "each",
                    1,
                    4250000.00,
                    {"masterformat": "26 32 13", "cpwd": "E-2.1"},
                ),
                (
                    "9.3",
                    "Main LT panel & floor distribution boards, IS 8623, fully wired",
                    "lsum",
                    1,
                    3850000.00,
                    {"masterformat": "26 24 00", "cpwd": "E-3.1"},
                ),
                (
                    "9.4",
                    "Point wiring with FRLS copper conductor in concealed conduit (wiring)",
                    "each",
                    3200,
                    1450.00,
                    {"masterformat": "26 27 00", "cpwd": "E-4.1"},
                ),
                (
                    "9.5",
                    "LED recessed luminaires 36W for offices, BIS-marked (LED batti)",
                    "each",
                    1850,
                    1850.00,
                    {"masterformat": "26 51 00", "cpwd": "E-5.1"},
                ),
                (
                    "9.6",
                    "Cable tray GI perforated 300-600 mm with covers & supports",
                    "m",
                    3600,
                    685.00,
                    {"masterformat": "26 05 36", "cpwd": "E-6.1"},
                ),
                (
                    "9.7",
                    "XLPE armoured power cable 3.5C up to 300 sqmm, laid & terminated",
                    "m",
                    4200,
                    1250.00,
                    {"masterformat": "26 05 19", "cpwd": "E-7.1"},
                ),
                (
                    "9.8",
                    "Earthing stations with maintenance-free electrode, IS 3043 (earthing)",
                    "each",
                    28,
                    18500.00,
                    {"masterformat": "26 05 26", "cpwd": "E-8.1"},
                ),
                (
                    "9.9",
                    "Lightning protection system, ESE / conventional, IS/IEC 62305",
                    "lsum",
                    1,
                    850000.00,
                    {"masterformat": "26 41 00", "cpwd": "E-9.1"},
                ),
                (
                    "9.10",
                    "Fire alarm system, addressable, with detectors & panel, IS 2189 (NBC 2016)",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "28 31 00", "cpwd": "E-10.1"},
                ),
                (
                    "9.11",
                    "Structured cabling Cat-6A, data outlets, racks & backbone fibre",
                    "lsum",
                    1,
                    2250000.00,
                    {"masterformat": "27 10 00", "cpwd": "E-11.1"},
                ),
                (
                    "9.12",
                    "CCTV & access-control system with NVR, IP cameras & door controllers",
                    "lsum",
                    1,
                    1950000.00,
                    {"masterformat": "28 23 00", "cpwd": "E-12.1"},
                ),
            ],
        ),
        # ── 10. HVAC & Lifts (Vertical Transport) ─────────────────────
        (
            "10",
            "HVAC & Lifts",
            {"masterformat": "23 00 00", "cpwd": "DSR-HVAC"},
            [
                (
                    "10.1",
                    "VRF air-conditioning system, 480 TR, with indoor units & refrigerant piping",
                    "lsum",
                    1,
                    18500000.00,
                    {"masterformat": "23 81 00", "cpwd": "H-1.1"},
                ),
                (
                    "10.2",
                    "Basement & toilet mechanical ventilation with jet fans, NBC 2016",
                    "lsum",
                    1,
                    2850000.00,
                    {"masterformat": "23 34 00", "cpwd": "H-2.1"},
                ),
                (
                    "10.3",
                    "Passenger lift 13-person 1.5 m/s, MRL gearless, 6 stops, IS 14665 (lift)",
                    "each",
                    3,
                    3850000.00,
                    {"masterformat": "14 21 00", "cpwd": "H-3.1"},
                ),
                (
                    "10.4",
                    "Service / stretcher lift 1600 kg, 7 stops, with auto-rescue device",
                    "each",
                    1,
                    4650000.00,
                    {"masterformat": "14 21 00", "cpwd": "H-3.2"},
                ),
                (
                    "10.5",
                    "Building management system (BMS) integrating HVAC, electrical & fire",
                    "lsum",
                    1,
                    3250000.00,
                    {"masterformat": "25 50 00", "cpwd": "H-4.1"},
                ),
            ],
        ),
        # ── 11. Facade & Glazing (Envelope) ───────────────────────────
        (
            "11",
            "Facade & Glazing",
            {"masterformat": "08 44 00", "cpwd": "DSR-FACADE"},
            [
                (
                    "11.1",
                    "Unitised curtain-wall DGU 6-12-6, low-E, thermal-break aluminium (kaanch deewar)",
                    "m2",
                    2800,
                    8850.00,
                    {"masterformat": "08 44 13", "cpwd": "F-1.1"},
                ),
                (
                    "11.2",
                    "Aluminium glazed windows openable, anodised, DGU, IS 1948 (khidki)",
                    "m2",
                    1450,
                    6250.00,
                    {"masterformat": "08 51 13", "cpwd": "F-2.1"},
                ),
                (
                    "11.3",
                    "ACP cladding 4 mm FR-grade on aluminium sub-frame (ACP cladding)",
                    "m2",
                    1850,
                    3850.00,
                    {"masterformat": "07 42 13", "cpwd": "F-3.1"},
                ),
                (
                    "11.4",
                    "Structural-glazing spider fitting at entrance atrium, 19 mm toughened",
                    "m2",
                    320,
                    11500.00,
                    {"masterformat": "08 44 26", "cpwd": "F-4.1"},
                ),
                (
                    "11.5",
                    "Aluminium louvres / fins for solar shading on south & west facade",
                    "m2",
                    680,
                    4250.00,
                    {"masterformat": "10 71 13", "cpwd": "F-5.1"},
                ),
            ],
        ),
        # ── 12. Waterproofing & Roofing (CPWD Sub-head 22) ────────────
        (
            "12",
            "Waterproofing & Roofing",
            {"masterformat": "07 00 00", "cpwd": "DSR-22"},
            [
                (
                    "12.1",
                    "APP-modified bitumen membrane water-proofing on terrace, 4 mm (chhat seal)",
                    "m2",
                    1450,
                    685.00,
                    {"masterformat": "07 52 00", "cpwd": "22.10"},
                ),
                (
                    "12.2",
                    "Box-type water-proofing in toilets & wet areas with brick-bat coba",
                    "m2",
                    980,
                    985.00,
                    {"masterformat": "07 14 00", "cpwd": "22.5"},
                ),
                (
                    "12.3",
                    "Crystalline water-proofing to basement raft & retaining walls (negative side)",
                    "m2",
                    1850,
                    485.00,
                    {"masterformat": "07 16 00", "cpwd": "22.20"},
                ),
                (
                    "12.4",
                    "Heat-reflective china-mosaic / cool-roof finish over terrace screed",
                    "m2",
                    1450,
                    385.00,
                    {"masterformat": "07 50 00", "cpwd": "22.30"},
                ),
                (
                    "12.5",
                    "Terrace insulation EPS + screed protective layer over membrane",
                    "m2",
                    1450,
                    545.00,
                    {"masterformat": "07 22 00", "cpwd": "22.35"},
                ),
            ],
        ),
        # ── 13. Road Work & External Development (CPWD Sub-head 16) ───
        (
            "13",
            "Road Work & External Development",
            {"masterformat": "32 00 00", "cpwd": "DSR-16"},
            [
                (
                    "13.1",
                    "Bituminous flexible pavement (GSB + WMM + DBM + BC), internal roads",
                    "m2",
                    1800,
                    1650.00,
                    {"masterformat": "32 12 16", "cpwd": "16.50"},
                ),
                (
                    "13.2",
                    "Interlocking concrete-block paving 80 mm in parking & walkways (paver)",
                    "m2",
                    1200,
                    985.00,
                    {"masterformat": "32 14 13", "cpwd": "16.60"},
                ),
                (
                    "13.3",
                    "RCC compound boundary wall 2.4 m high with coping (chardiwari)",
                    "m",
                    420,
                    4850.00,
                    {"masterformat": "32 31 00", "cpwd": "16.30"},
                ),
                (
                    "13.4",
                    "Cantilever sliding entrance gate, MS, motorised with boom barrier",
                    "lsum",
                    1,
                    1450000.00,
                    {"masterformat": "32 31 13", "cpwd": "16.35"},
                ),
                (
                    "13.5",
                    "Soft landscaping — lawn, shrubs, trees & drip irrigation (bagwani)",
                    "m2",
                    1600,
                    485.00,
                    {"masterformat": "32 90 00", "cpwd": "16.80"},
                ),
                (
                    "13.6",
                    "Storm-water surface drains RCC with gratings along roads",
                    "m",
                    680,
                    2250.00,
                    {"masterformat": "33 40 00", "cpwd": "16.70"},
                ),
                (
                    "13.7",
                    "Solar PV rooftop grid-tied 150 kWp with net-metering (MNRE compliant)",
                    "lsum",
                    1,
                    7250000.00,
                    {"masterformat": "48 14 00", "cpwd": "16.90"},
                ),
                (
                    "13.8",
                    "External area lighting on poles, LED, with feeder pillars (bahar batti)",
                    "each",
                    48,
                    32500.00,
                    {"masterformat": "26 56 00", "cpwd": "16.85"},
                ),
            ],
        ),
    ],
    # CPWD-style markups: contractor overheads & profit folded into a single
    # tendered percentage above DSR; cess and GST carried separately.
    markups=[
        ("Contractor Overheads & Profit (CP&OH)", 15.0, "overhead", "direct_cost"),
        ("Contingencies", 3.0, "contingency", "direct_cost"),
        ("Building & Other Construction Workers Cess (1%)", 1.0, "tax", "direct_cost"),
        ("Goods & Services Tax (GST 18%)", 18.0, "tax", "cumulative"),
    ],
    total_months=24,
    tender_name="Main Civil & Services Contract (Composite EPC)",
    tender_companies=[
        ("Larsen & Toubro Construction", "tenders@lntecc.com", 0.98),
        ("Shapoorji Pallonji & Co. Ltd.", "bids@shapoorji.in", 1.04),
        ("NBCC (India) Ltd.", "tender@nbccindia.co.in", 1.01),
    ],
    project_metadata={
        "address": "Lodhi Road, CGO Complex, New Delhi 110003",
        "client": "Central Public Works Department (CPWD), Ministry of Housing & Urban Affairs",
        "architect": "CPWD Chief Architect's Organisation",
        "structural_consultant": "STUP Consultants Pvt. Ltd.",
        "gfa_m2": 7800,
        "storeys": "G+5 with one basement",
        "structure_system": "RCC special moment-resisting frame (SMRF)",
        "seismic_zone": "Zone IV (IS 1893:2016, Z=0.24, I=1.5, R=5)",
        "design_codes": "IS 456, IS 1893:2016, IS 13920, IS 875, IS 800, NBC 2016",
        "schedule_of_rates": "CPWD DSR 2021 (Delhi) + Delhi Analysis of Rates",
        "measurement_standard": "IS 1200 (mode of measurement)",
        "sustainability": "GRIHA 4-star target; ECBC-compliant envelope; 150 kWp rooftop solar; RWH per CGWB",
        "tax_note": "All BoQ rates are GST-exclusive; GST at 18% (works contract HSN 9954) applied as a separate line; BOCW cess 1% applies; TDS as per Income-tax Act",
        "statutory": "RERA registration not applicable (Govt. building); fire NOC per Delhi Fire Service / NBC 2016 Part 4; structural safety certificate per local bye-laws",
        "labour_compliance": "CPWD Form contracts; minimum wages (Delhi); BOCW Act 1996; CLRA Act 1970",
        "headline_cost_inr": "approx. 38 crore (380 million INR)",
    },
)
