# -*- coding: utf-8 -*-
"""Comprehensive translator for the 2300 untranslated mn.ts entries.

Strategy:
1. Build a phrase-level dictionary keyed by exact English (case-sensitive)
   covering the most common short strings (buttons, labels, headers).
2. Build a word-level glossary for token-by-token translation of less common
   medium-length strings.
3. Protect placeholders ({{x}}, {x}, %s, :param), HTML, and technical
   acronyms before translation.
4. Apply sentence-pattern replacements for common construction-software
   phrases like "X to Y", "Failed to X", "Loading X...".
5. Fall back to keeping the English string if heuristics can't translate it
   confidently (so build never breaks).
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_PATH = ROOT / "frontend" / "src" / "app" / "locales" / "en.ts"
MN_PATH = ROOT / "frontend" / "src" / "app" / "locales" / "mn.ts"
UNTRANS_JSON = ROOT / "scripts" / "_mn_all_untranslated.json"

# ---------------------------------------------------------------------------
# Protected tokens (never translated)
# ---------------------------------------------------------------------------
PROTECTED = [
    "OpenConstructionERP", "OpenEstimate", "OpenEstimator",
    "OpenEstimator.io", "OpenEstimate.io",
    "BIM", "IFC", "DWG", "DGN", "RVT", "DAE", "COLLADA", "Revit",
    "GAEB", "DIN", "DIN 276", "NRM", "NRM 1/2", "NRM 2", "MasterFormat",
    "UniFormat", "Uniclass", "OmniClass", "BIM 360",
    "SAP", "Procore", "Primavera", "PlanRadar", "MS Project",
    "PERT", "CPM", "CPI", "SPI", "MEP", "EVM", "ESG",
    "RFI", "RFIs", "NCR", "NCRs",
    "BAC", "EAC", "PV", "EV", "AC", "VAC", "SV", "ETC", "TCPI",
    "CWICR", "DDC", "DDC cad2data", "cad2data", "Qdrant", "LanceDB", "Three.js",
    "BOQ", "BOQs", "BoQ", "HuggingFace", "Hugging Face", "JSON", "API",
    "OCR", "PDF", "CSV", "XML", "Excel", "Word", "VAT",
    "OpenAI", "Anthropic", "Claude", "GPT-4", "GPT-4o", "GPT-4 Turbo",
    "Gemini", "Claude 3.5",
    "Slack", "Telegram", "Microsoft Teams", "Teams", "Google", "Outlook",
    "iCal", "Webhook", "Webhooks", "HTTP", "HTTP POST", "POST", "SMTP", "URL",
    "ISO 19650", "ISO 4217", "AACE", "AGPL-3.0", "GitHub", "LinkedIn",
    "X/Twitter", "Twitter", "BGE-M3", "BGE", "BAAI", "INT8", "FP32",
    "S-Curve", "S-curve", "Monte Carlo", "Gantt", "DACH", "SQLite",
    "Parquet", "BKI", "BCIS", "RSMeans", "SNIP", "GESN", "STABU",
    "Birim Fiyat", "Sekisan", "SINAPI", "Computo", "DPGF", "KNR",
    "EUR", "USD", "MNT", "XAF", "BRL", "INR", "GBP", "JPY", "CNY",
    "TBD", "RFQ", "LLM", "QA", "OCEP", "CRM", "CAD", "AI",
    "WBS", "FX", "PRO", "STD", "HVAC", "ABC %", "ABC",
    "Pareto", "AGPL", "BSt 500", "B500", "C30/37", "F90", "S2",
    "Ctrl", "Ctrl+D", "Ctrl+E", "Ctrl+I", "Ctrl+L", "Ctrl+/",
    "Ctrl+Y", "Ctrl+Z", "Ctrl+Shift+V", "Ctrl+Enter", "Cmd",
    "X81", "X83", "X84", "GAEB X83", "GAEB XML",
    "MB", "GB", "kg", "m2", "m3", "m²", "m³",
    "Q3", "Q4", "Q1", "Q2",
    "Berlin", "Munich",
    "JWT", "OAuth", "SSO",
    ".rvt", ".ifc", ".dwg", ".dgn", ".pdf", ".xlsx", ".csv", ".json", ".xml",
    "1.0", "2.0", "3.0", "4D", "5D",
    "n8n", "Zapier",
]

INTERP_RE = re.compile(r"\{\{[^}]+\}\}")
INTERP2_RE = re.compile(r"\{[a-zA-Z_][a-zA-Z0-9_]*\}")
HTML_RE = re.compile(r"</?[a-zA-Z][^>]*>")
PARAM_RE = re.compile(r":[a-zA-Z_][a-zA-Z0-9_]*\b")
PCT_RE = re.compile(r"%[sd]")
NUM_RE = re.compile(r"\b\d+([.,]\d+)?[%kMG]?\b")


def protect(text: str) -> tuple[str, list[str]]:
    """Replace tokens we must keep verbatim with sentinels."""
    tokens: list[str] = []

    def keep(m: re.Match) -> str:
        tokens.append(m.group(0))
        return f"\x00{len(tokens)-1}\x00"

    text = INTERP_RE.sub(keep, text)
    text = INTERP2_RE.sub(keep, text)
    text = HTML_RE.sub(keep, text)
    text = PARAM_RE.sub(keep, text)
    text = PCT_RE.sub(keep, text)
    # Protected technical terms (longest first to avoid partial matches)
    for term in sorted(PROTECTED, key=len, reverse=True):
        pat = re.compile(r"(?<!\w)" + re.escape(term) + r"(?!\w)")
        text = pat.sub(keep, text)
    return text, tokens


def restore(text: str, tokens: list[str]) -> str:
    def back(m: re.Match) -> str:
        idx = int(m.group(1))
        return tokens[idx] if 0 <= idx < len(tokens) else m.group(0)
    return re.sub(r"\x00(\d+)\x00", back, text)


# ---------------------------------------------------------------------------
# Phrase-level dictionary — full string matches (case-sensitive)
# These are checked FIRST as exact matches before token-level translation.
# ---------------------------------------------------------------------------
PHRASES: dict[str, str] = {
    # Common UI verbs/actions
    "Save": "Хадгалах",
    "Saved": "Хадгалагдсан",
    "Saving...": "Хадгалж байна...",
    "Cancel": "Цуцлах",
    "Close": "Хаах",
    "Delete": "Устгах",
    "Edit": "Засах",
    "Add": "Нэмэх",
    "Remove": "Хасах",
    "Update": "Шинэчлэх",
    "Updated": "Шинэчлэгдсэн",
    "Create": "Үүсгэх",
    "Created": "Үүсгэгдсэн",
    "Open": "Нээх",
    "View": "Үзэх",
    "Export": "Экспортлох",
    "Import": "Импортлох",
    "Download": "Татах",
    "Upload": "Байршуулах",
    "Submit": "Илгээх",
    "Send": "Илгээх",
    "Search": "Хайх",
    "Filter": "Шүүх",
    "Refresh": "Сэргээх",
    "Reset": "Дахин тохируулах",
    "Apply": "Хэрэглэх",
    "Continue": "Үргэлжлүүлэх",
    "Back": "Буцах",
    "Next": "Дараах",
    "Previous": "Өмнөх",
    "Loading...": "Ачаалж байна...",
    "Saving": "Хадгалж байна",
    "Loading": "Ачаалж байна",
    "Yes": "Тийм",
    "No": "Үгүй",
    "OK": "За",
    "Done": "Дууссан",
    "Pending": "Хүлээгдэж байна",
    "Active": "Идэвхтэй",
    "Inactive": "Идэвхгүй",
    "Archived": "Архивлагдсан",
    "Approved": "Зөвшөөрөгдсөн",
    "Rejected": "Татгалзсан",
    "Draft": "Ноорог",
    "Published": "Нийтлэгдсэн",
    "Completed": "Дууссан",
    "In Progress": "Хийгдэж байгаа",
    "In progress": "Хийгдэж байгаа",
    "Not started": "Эхлээгүй",
    "Failed": "Амжилтгүй",
    "Success": "Амжилттай",
    "Successfully": "Амжилттай",
    "Error": "Алдаа",
    "Warning": "Анхааруулга",
    "Info": "Мэдээлэл",
    "Information": "Мэдээлэл",
    "Settings": "Тохиргоо",
    "Help": "Тусламж",
    "About": "Тухай",
    "Login": "Нэвтрэх",
    "Logout": "Гарах",
    "Sign in": "Нэвтрэх",
    "Sign out": "Гарах",
    "Sign up": "Бүртгүүлэх",
    "Email": "И-мэйл",
    "Password": "Нууц үг",
    "Username": "Хэрэглэгчийн нэр",
    "Name": "Нэр",
    "Description": "Тайлбар",
    "Notes": "Тэмдэглэл",
    "Comments": "Сэтгэгдэл",
    "Date": "Огноо",
    "Time": "Цаг",
    "Status": "Төлөв",
    "Type": "Төрөл",
    "Category": "Ангилал",
    "Tags": "Шошго",
    "Title": "Гарчиг",
    "Subject": "Сэдэв",
    "Body": "Агуулга",
    "Total": "Нийт",
    "Subtotal": "Дэд дүн",
    "Quantity": "Тоо хэмжээ",
    "Unit": "Нэгж",
    "Price": "Үнэ",
    "Cost": "Өртөг",
    "Amount": "Дүн",
    "Rate": "Тариф",
    "Currency": "Валют",
    "Project": "Төсөл",
    "Projects": "Төслүүд",
    "Position": "Байрлал",
    "Positions": "Байрлалууд",
    "Section": "Хэсэг",
    "Sections": "Хэсгүүд",
    "Group": "Бүлэг",
    "Groups": "Бүлгүүд",
    "User": "Хэрэглэгч",
    "Users": "Хэрэглэгчид",
    "Team": "Баг",
    "Members": "Гишүүд",
    "Role": "Үүрэг",
    "Permission": "Эрх",
    "Permissions": "Эрхүүд",
    "Profile": "Профайл",
    "Account": "Бүртгэл",
    "Dashboard": "Самбар",
    "Home": "Нүүр",
    "Menu": "Цэс",
    "Navigation": "Навигаци",
    "Notifications": "Мэдэгдэл",
    "Notification": "Мэдэгдэл",
    "Messages": "Зурвас",
    "Files": "Файлууд",
    "File": "Файл",
    "Folder": "Хавтас",
    "Folders": "Хавтсууд",
    "Document": "Баримт бичиг",
    "Documents": "Баримт бичиг",
    "Report": "Тайлан",
    "Reports": "Тайлан",
    "Analytics": "Аналитик",
    "Statistics": "Статистик",
    "Tasks": "Даалгавар",
    "Task": "Даалгавар",
    "Schedule": "Хуваарь",
    "Calendar": "Календарь",
    "Activity": "Үйл ажиллагаа",
    "Activities": "Үйл ажиллагаа",
    "Event": "Үйл явдал",
    "Events": "Үйл явдал",
    "History": "Түүх",
    "Log": "Бүртгэл",
    "Logs": "Бүртгэл",
    "Audit": "Аудит",
    "Audit Log": "Аудитын бүртгэл",
    "Version": "Хувилбар",
    "Versions": "Хувилбарууд",
    "Tools": "Хэрэгсэл",
    "Modules": "Модулиуд",
    "Module": "Модуль",
    "Marketplace": "Маркетплейс",
    "Catalog": "Каталог",
    "Resource": "Нөөц",
    "Resources": "Нөөц",
    "Material": "Материал",
    "Materials": "Материал",
    "Equipment": "Тоног төхөөрөмж",
    "Labor": "Хөдөлмөр",
    "Suppliers": "Нийлүүлэгчид",
    "Supplier": "Нийлүүлэгч",
    "Vendor": "Нийлүүлэгч",
    "Vendors": "Нийлүүлэгчид",
    "Subcontractor": "Туслан гүйцэтгэгч",
    "Subcontractors": "Туслан гүйцэтгэгчид",
    "Contractor": "Гүйцэтгэгч",
    "Contractors": "Гүйцэтгэгчид",
    "Client": "Үйлчлүүлэгч",
    "Clients": "Үйлчлүүлэгчид",
    "Customer": "Үйлчлүүлэгч",
    "Risk": "Эрсдэл",
    "Risks": "Эрсдэлүүд",
    "Quality": "Чанар",
    "Safety": "Аюулгүй байдал",
    "Compliance": "Дагалт",
    "Tender": "Тендер",
    "Tenders": "Тендерүүд",
    "Bid": "Санал",
    "Bids": "Саналууд",
    "Tendering": "Тендер",
    "Bidding": "Тендер",
    "Procurement": "Худалдан авалт",
    "Contract": "Гэрээ",
    "Contracts": "Гэрээнүүд",
    "Change Order": "Өөрчлөлтийн тушаал",
    "Change Orders": "Өөрчлөлтийн тушаал",
    "Invoice": "Нэхэмжлэх",
    "Invoices": "Нэхэмжлэх",
    "Payment": "Төлбөр",
    "Payments": "Төлбөр",
    "Budget": "Төсөв",
    "Budgets": "Төсвүүд",
    "Estimate": "Тооцоо",
    "Estimates": "Тооцоо",
    "Estimation": "Тооцоолол",
    "Estimator": "Тооцоологч",
    "Estimators": "Тооцоологчид",
    "Architect": "Архитектор",
    "Architects": "Архитекторууд",
    "Engineer": "Инженер",
    "Engineers": "Инженерүүд",
    "Drawing": "Зураг",
    "Drawings": "Зургууд",
    "Model": "Загвар",
    "Models": "Загварууд",
    "Element": "Элемент",
    "Elements": "Элементүүд",
    "Site": "Талбай",
    "Construction": "Барилга",
    "Building": "Барилга",
    "Buildings": "Барилгууд",
    "Floor": "Давхар",
    "Floors": "Давхрууд",
    "Level": "Түвшин",
    "Levels": "Түвшинүүд",
    "Photo": "Зураг",
    "Photos": "Зургууд",
    "Picture": "Зураг",
    "Image": "Зураг",
    "Images": "Зургууд",
    "Inspection": "Шалгалт",
    "Inspections": "Шалгалт",
    "Issue": "Асуудал",
    "Issues": "Асуудлууд",
    "Defect": "Гэмтэл",
    "Defects": "Гэмтэлүүд",
    "Punch": "Дутагдал",
    "Punch List": "Дутагдлын жагсаалт",
    "Field Report": "Талбайн тайлан",
    "Field Reports": "Талбайн тайлан",
    "Meeting": "Уулзалт",
    "Meetings": "Уулзалт",
    "Transmittal": "Дамжуулалт",
    "Transmittals": "Дамжуулалт",
    "Submittal": "Илгээлт",
    "Submittals": "Илгээлт",
    "Correspondence": "Захидал",
    "Comment": "Сэтгэгдэл",
    "Markup": "Тэмдэглэгээ",
    "Markups": "Тэмдэглэгээ",
    "Annotation": "Тайлбар",
    "Annotations": "Тайлбар",
    "Required": "Шаардлагатай",
    "Optional": "Сонголтын",
    "Recommended": "Зөвлөмжтэй",
    "All": "Бүгд",
    "None": "Байхгүй",
    "Any": "Дурын",
    "Other": "Бусад",
    "More": "Илүү",
    "Less": "Бага",
    "Show": "Харуулах",
    "Hide": "Нуух",
    "Show more": "Илүү харуулах",
    "Show less": "Бага харуулах",
    "Expand": "Дэлгэрэх",
    "Collapse": "Хураах",
    "Select": "Сонгох",
    "Selected": "Сонгогдсон",
    "Choose": "Сонгох",
    "Pick": "Сонгох",
    "Confirm": "Баталгаажуулах",
    "Confirmed": "Баталгаажсан",
    "Approve": "Зөвшөөрөх",
    "Reject": "Татгалзах",
    "Sort": "Эрэмбэлэх",
    "Sort by": "Эрэмбэлэх",
    "Group by": "Бүлэглэх",
    "Filter by": "Шүүх",
    "Print": "Хэвлэх",
    "Copy": "Хуулах",
    "Cut": "Тасдах",
    "Paste": "Буулгах",
    "Duplicate": "Хуулбарлах",
    "Move": "Шилжүүлэх",
    "Rename": "Нэр өөрчлөх",
    "Replace": "Орлуулах",
    "Insert": "Оруулах",
    "Click": "Дарах",
    "Click here": "Энд дарна уу",
    "Try again": "Дахин оролдох",
    "Retry": "Дахин оролдох",
    "Reload": "Дахин ачаалах",
    "Disabled": "Идэвхгүй",
    "Enabled": "Идэвхтэй",
    "Enable": "Идэвхжүүлэх",
    "Disable": "Идэвхгүй болгох",
    "On": "Асаалттай",
    "Off": "Унтраалттай",
    "Available": "Боломжтой",
    "Unavailable": "Боломжгүй",
    "Coming soon": "Удахгүй",
    "New": "Шинэ",
    "Recent": "Сүүлийн",
    "Latest": "Хамгийн сүүлийн",
    "Old": "Хуучин",
    "Archive": "Архивлах",
    "Restore": "Сэргээх",
    "Permanent": "Байнгын",
    "Temporary": "Түр",
    "Public": "Нийтийн",
    "Private": "Хувийн",
    "Shared": "Хуваалцсан",
    "Share": "Хуваалцах",
    "Link": "Холбоос",
    "Links": "Холбоосууд",
    "Address": "Хаяг",
    "Phone": "Утас",
    "Website": "Вэбсайт",
    "Company": "Компани",
    "Organization": "Байгууллага",
    "Department": "Хэлтэс",
    "Location": "Байршил",
    "Region": "Бүс",
    "Country": "Улс",
    "City": "Хот",
    "State": "Муж",
    "Postcode": "Зип код",
    "Zip": "Зип",
    "Language": "Хэл",
    "Theme": "Загвар",
    "Dark": "Харанхуй",
    "Light": "Цайвар",
    "System": "Систем",
    "Database": "Өгөгдлийн сан",
    "Server": "Сервер",
    "Cloud": "Үүл",
    "Local": "Дотоод",
    "Online": "Онлайн",
    "Offline": "Оффлайн",
    "Sync": "Синхрон",
    "Synced": "Синхрончилсон",
    "Backup": "Нөөц хуулбар",
    "Restore from backup": "Нөөцөөс сэргээх",
    "Integration": "Интеграц",
    "Integrations": "Интеграцууд",
    "Workflow": "Ажлын урсгал",
    "Workflows": "Ажлын урсгалууд",
    "Pipeline": "Шугам",
    "Step": "Алхам",
    "Steps": "Алхамууд",
    "Stage": "Шат",
    "Stages": "Шатууд",
    "Phase": "Үе шат",
    "Phases": "Үе шатууд",
    "Milestone": "Чухал үе",
    "Milestones": "Чухал үе",
    "Deadline": "Эцсийн хугацаа",
    "Due Date": "Хүлээх огноо",
    "Start Date": "Эхлэх огноо",
    "End Date": "Дуусах огноо",
    "Start date": "Эхлэх огноо",
    "End date": "Дуусах огноо",
    "Duration": "Үргэлжлэх хугацаа",
    "Progress": "Явц",
    "Completed at": "Дууссан огноо",
    "Created at": "Үүсгэсэн огноо",
    "Updated at": "Шинэчилсэн огноо",
    "Last modified": "Сүүлд өөрчилсөн",
    "Created by": "Үүсгэсэн",
    "Modified by": "Өөрчилсөн",
    "Assigned to": "Хариуцагч",
    "Assigned": "Хариуцагчтай",
    "Unassigned": "Хариуцагчгүй",
    "Owner": "Эзэмшигч",
    "Members only": "Зөвхөн гишүүд",
    "Anyone": "Хэн ч",
    "Read": "Унших",
    "Write": "Бичих",
    "Read-only": "Зөвхөн унших",
    "Full access": "Бүрэн эрх",
    "No access": "Эрхгүй",
    "Access denied": "Эрх хаагдсан",
    "Not found": "Олдсонгүй",
    "Page not found": "Хуудас олдсонгүй",
    "Forbidden": "Хориотой",
    "Unauthorized": "Эрхгүй",
    "Bad request": "Буруу хүсэлт",
    "Server error": "Серверийн алдаа",
    "Network error": "Сүлжээний алдаа",
    "Connection error": "Холболтын алдаа",
    "Try later": "Дараа оролдоно уу",
    "Please try again": "Дахин оролдоно уу",
    "Please wait": "Хүлээнэ үү",
    "Wait": "Хүлээх",
    "Saved successfully": "Амжилттай хадгалагдлаа",
    "Updated successfully": "Амжилттай шинэчилэгдлээ",
    "Deleted successfully": "Амжилттай устгагдлаа",
    "Created successfully": "Амжилттай үүсгэгдлээ",
    "Yes, delete": "Тийм, устгах",
    "Yes, continue": "Тийм, үргэлжлүүлэх",
    "Are you sure?": "Та итгэлтэй байна уу?",
    "This action cannot be undone": "Энэ үйлдлийг буцаах боломжгүй",
    "Welcome": "Тавтай морил",
    "Welcome back": "Эргэн тавтай морил",
    "Getting started": "Эхлэх",
    "Get started": "Эхлэх",
    "Learn more": "Дэлгэрэнгүй",
    "Read more": "Дэлгэрэнгүй",
    "Read documentation": "Баримт бичигийг унших",
    "Documentation": "Баримт бичиг",
    "Tutorial": "Заавар",
    "Guide": "Зааварчилгаа",
    "Examples": "Жишээ",
    "Example": "Жишээ",
    "Demo": "Демо",
    "Preview": "Урьдчилан үзэх",
    "Print preview": "Хэвлэхээ урьдчилан үзэх",
    "Generate": "Үүсгэх",
    "Generating": "Үүсгэж байна",
    "Generating...": "Үүсгэж байна...",
    "Processing": "Боловсруулж байна",
    "Processing...": "Боловсруулж байна...",
    "Analyzing": "Шинжилж байна",
    "Analyzing...": "Шинжилж байна...",
    "Connecting": "Холбогдож байна",
    "Connecting...": "Холбогдож байна...",
    "Connected": "Холбогдсон",
    "Disconnected": "Салгасан",
    "Disconnect": "Салгах",
    "Connect": "Холбогдох",
    "Reconnect": "Дахин холбогдох",
    "Source": "Эх сурвалж",
    "Sources": "Эх сурвалжууд",
    "Target": "Зорилго",
    "Destination": "Очих газар",
    "From": "Эхлэл",
    "To": "Эцэс",
    "From:": "Эхлэл:",
    "To:": "Эцэс:",
    "Min": "Доод",
    "Max": "Дээд",
    "Average": "Дундаж",
    "Median": "Дундах",
    "Range": "Хүрээ",
    "Count": "Тоо",
    "Sum": "Нийлбэр",
    "Width": "Өргөн",
    "Height": "Өндөр",
    "Length": "Урт",
    "Depth": "Гүн",
    "Area": "Талбай",
    "Volume": "Эзэлхүүн",
    "Weight": "Жин",
    "Size": "Хэмжээ",
    "Color": "Өнгө",
    "Style": "Загвар",
    "Format": "Формат",
    "Templates": "Загвар",
    "Template": "Загвар",
    "Configuration": "Тохиргоо",
    "Config": "Тохиргоо",
    "Options": "Сонголтууд",
    "Preferences": "Тохиргоо",
    "Field": "Талбар",
    "Fields": "Талбарууд",
    "Column": "Багана",
    "Columns": "Баганууд",
    "Row": "Мөр",
    "Rows": "Мөрүүд",
    "Table": "Хүснэгт",
    "List": "Жагсаалт",
    "Grid": "Сүлжээ",
    "Card": "Карт",
    "Tab": "Таб",
    "Tabs": "Табууд",
    "Page": "Хуудас",
    "Pages": "Хуудсууд",
    "Code": "Код",
    "Number": "Дугаар",
    "ID": "ID",
    "Reference": "Лавлагаа",
    "References": "Лавлагаа",
    "Index": "Индекс",
    "Order": "Дараалал",
    "Sequence": "Дараалал",
    "First": "Эхний",
    "Last": "Сүүлийн",
    "Default": "Үндсэн",
    "Custom": "Захиалгат",
    "Standard": "Стандарт",
    "Advanced": "Дэвшилт",
    "Basic": "Үндсэн",
    "Beta": "Бета",
    "Stable": "Тогтвортой",
    "Experimental": "Туршилтын",
    "Deprecated": "Хуучирсан",
    "Legacy": "Өвлөгдсөн",
    "Modern": "Орчин үеийн",
    "Today": "Өнөөдөр",
    "Yesterday": "Өчигдөр",
    "Tomorrow": "Маргааш",
    "This week": "Энэ долоо хоног",
    "This month": "Энэ сар",
    "This year": "Энэ жил",
    "Last week": "Өнгөрсөн долоо хоног",
    "Last month": "Өнгөрсөн сар",
    "Last year": "Өнгөрсөн жил",
    "Hour": "Цаг",
    "Hours": "Цагууд",
    "Minute": "Минут",
    "Minutes": "Минут",
    "Second": "Секунд",
    "Seconds": "Секунд",
    "Day": "Өдөр",
    "Days": "Өдрүүд",
    "Week": "Долоо хоног",
    "Weeks": "Долоо хоног",
    "Month": "Сар",
    "Months": "Сарууд",
    "Year": "Жил",
    "Years": "Жилүүд",
    "January": "1-р сар",
    "February": "2-р сар",
    "March": "3-р сар",
    "April": "4-р сар",
    "May": "5-р сар",
    "June": "6-р сар",
    "July": "7-р сар",
    "August": "8-р сар",
    "September": "9-р сар",
    "October": "10-р сар",
    "November": "11-р сар",
    "December": "12-р сар",
    "Monday": "Даваа",
    "Tuesday": "Мягмар",
    "Wednesday": "Лхагва",
    "Thursday": "Пүрэв",
    "Friday": "Баасан",
    "Saturday": "Бямба",
    "Sunday": "Ням",
    # Construction-domain phrases
    "Bill of Quantities": "Ажил материалын жагсаалт",
    "Quantity Surveyor": "Тоо хэмжээний зураач",
    "Quantity surveyors": "Тоо хэмжээний зураачид",
    "General Contractor": "Ерөнхий гүйцэтгэгч",
    "General contractors": "Ерөнхий гүйцэтгэгчид",
    "Cost Estimator": "Өртгийн тооцоологч",
    "Cost estimators": "Өртгийн тооцоологчид",
    "Real estate developers": "Үл хөдлөх хөгжүүлэгчид",
    "Real Estate Developer": "Үл хөдлөх хөгжүүлэгч",
    "Project Manager": "Төслийн менежер",
    "Project managers": "Төслийн менежерүүд",
    "Cost Database": "Өртгийн өгөгдлийн сан",
    "Cost Databases": "Өртгийн өгөгдлийн сан",
    "Cost Model": "Өртгийн загвар",
    "Cost item": "Өртгийн зүйл",
    "Cost items": "Өртгийн зүйлс",
    "Cost code": "Өртгийн код",
    "Cost codes": "Өртгийн кодууд",
    "Unit rate": "Нэгжийн тариф",
    "Unit rates": "Нэгжийн тарифууд",
    "Unit price": "Нэгжийн үнэ",
    "Cost group": "Өртгийн бүлэг",
    "Cost groups": "Өртгийн бүлгүүд",
    "Cost breakdown": "Өртгийн задаргаа",
    "Cost summary": "Өртгийн хураангуй",
    "Project setup": "Төслийн тохиргоо",
    "Project details": "Төслийн дэлгэрэнгүй",
    "Project name": "Төслийн нэр",
    "Project type": "Төслийн төрөл",
    "Project status": "Төслийн төлөв",
    "Project info": "Төслийн мэдээлэл",
    "Project information": "Төслийн мэдээлэл",
    "Recent projects": "Сүүлийн төслүүд",
    "All projects": "Бүх төслүүд",
    "My projects": "Миний төслүүд",
    "New project": "Шинэ төсөл",
    "Create project": "Төсөл үүсгэх",
    "Create a project": "Төсөл үүсгэх",
    "Open project": "Төсөл нээх",
    "Project not found": "Төсөл олдсонгүй",
    "Quality Validation": "Чанарын баталгаажуулалт",
    "Validation": "Баталгаажуулалт",
    "Validate": "Баталгаажуулах",
    "Validation rules": "Баталгаажуулалтын дүрэм",
    "Validation report": "Баталгаажуулалтын тайлан",
    "Validation results": "Баталгаажуулалтын үр дүн",
    "What you can do": "Та юу хийж чадах вэ",
    "Why open source matters": "Нээлттэй эх кодын ач холбогдол",
    "Who is it for": "Хэнд зориулагдсан вэ",
    "Platform in numbers": "Платформ тоогоор",
    "Regional databases": "Бүс нутгийн өгөгдлийн сан",
    "Free & open source": "Үнэгүй, нээлттэй эх код",
    "Architects & engineers": "Архитекторууд ба инженерүүд",
    "Students & educators": "Оюутнууд ба багш нар",
    "Freelance consultants": "Бие даасан зөвлөхүүд",
    "Public sector & municipalities": "Төрийн салбар ба нутгийн захиргаа",
    "Import & Export": "Импорт, экспорт",
    "Tendering & Bids": "Тендер ба санал",
    "4D Scheduling": "4D хуваарь",
    "About AI features": "AI боломжуудын тухай",
    "Coming soon": "Удахгүй",
    "Try again": "Дахин оролдох",
    "Add a note...": "Тэмдэглэл нэмэх...",
    "Add to BOQ": "BOQ-д нэмэх",
    "Add all to BOQ": "Бүгдийг BOQ-д нэмэх",
    "Add selected to BOQ": "Сонгосныг BOQ-д нэмэх",
    "Sources:": "Эх сурвалжууд:",
    "AI Assistant": "AI туслах",
    "AI Advisor Error": "AI зөвлөгчийн алдаа",
    "Analyze Photo": "Зургийг шинжлэх",
    "Convert & Estimate": "Хөрвүүлэх ба тооцоолох",
    "Extract & Estimate": "Гаргаж авах ба тооцоолох",
    "Parse & Import": "Задлан шинжлэх ба импортлох",
    "Import & Parse": "Импортлох ба задлан шинжлэх",
    "Estimate generated": "Тооцоо үүсгэгдлээ",
    "Estimation failed": "Тооцоолол амжилтгүй",
    "Export coming soon": "Экспорт удахгүй",
    "BOQ saved successfully": "BOQ амжилттай хадгалагдлаа",
    "Powered by {{model}}": "{{model}}-ээр ажилладаг",
    "Supports: {{formats}}": "Дэмждэг: {{formats}}",
    "Generated in {{duration}}s using {{model}}": "{{model}} ашиглан {{duration}}с-д үүсгэгдсэн",
    "{{count}} items generated": "{{count}} зүйл үүсгэгдлээ",
    "Estimate generation failed": "Тооцоо үүсгэхэд алдаа гарлаа",
    "Name for this BOQ...": "Энэ BOQ-н нэр...",
    "-- Choose a project --": "-- Төсөл сонгох --",
    "e.g. Berlin": "ж.нь Berlin",
    "Describe your project...\\n\\nExample: ": "Төслөө тайлбарлана уу...\\n\\nЖишээ: ",
    "Accuracy": "Нарийвчлал",
    "Accuracy Range": "Нарийвчлалын хүрээ",
    "AACE Class": "AACE ангилал",
    "Definition": "Тодорхойлолт",
    "Definition Level": "Тодорхойлолтын түвшин",
    "Methodology": "Аргачлал",
    "Classification Metrics": "Ангиллын үзүүлэлт",
    "With classification": "Ангилалтай",
    "With unit rates": "Нэгжийн тарифтай",
    "Fully resourced": "Бүрэн нөөцтэй",
    "AI Assistant": "AI туслах",
    "Press Enter to add, Escape to cancel": "Нэмэхдээ Enter, цуцлахдаа Escape товчийг дарна уу",
    "Ask me anything about construction costs": "Барилгын өртгийн талаар асууж болно",
    "Ask about costs, materials, pricing...": "Өртөг, материал, үнийн талаар асуух...",
    "What is the average cost per m² of plaster?": "Шавардлагын м² тутамд ноогдох дундаж өртөг хэдэн вэ?",
    "Compare concrete prices by region": "Бүс бүсээр бетонны үнийг харьцуулах",
    "Suggest cheaper alternatives for steel": "Гангийн илүү хямд хувилбарууд санал болгох",
    "What are typical labor rates for electricians?": "Цахилгаанчдын ердийн цалин хэд вэ?",
    "Professional construction estimation workspace": "Барилгын тооцооллын мэргэжлийн ажлын талбар",
    "Reusable cost recipes for common construction elements": "Нийтлэг барилгын элементүүдэд зориулсан дахин ашиглах боломжтой өртгийн жор",
    "Try adjusting your search or filters": "Хайлт эсвэл шүүлтүүрийг өөрчилж үзнэ үү",
    # Login/auth
    "Enter your email and we'll send you a reset link.": "И-мэйлээ оруулна уу, бид нууц үг сэргээх холбоос илгээх болно.",
    "If an account exists for this email, you'll receive a password reset link shortly.": "Хэрэв энэ и-мэйлд бүртгэл байгаа бол та нууц үг сэргээх холбоосыг удахгүй хүлээж авна.",
    # Misc construction phrases
    "Add Tag": "Шошго нэмэх",
    "Add tag": "Шошго нэмэх",
    "Add comment": "Сэтгэгдэл нэмэх",
    "Add member": "Гишүүн нэмэх",
    "Add user": "Хэрэглэгч нэмэх",
    "Add file": "Файл нэмэх",
    "Add row": "Мөр нэмэх",
    "Add column": "Багана нэмэх",
    "Add item": "Зүйл нэмэх",
    "Add new": "Шинэ нэмэх",
    "No results": "Үр дүн байхгүй",
    "No data": "Өгөгдөл байхгүй",
    "No items": "Зүйл байхгүй",
    "No projects": "Төсөл байхгүй",
    "No files": "Файл байхгүй",
    "No comments": "Сэтгэгдэл байхгүй",
    "No notifications": "Мэдэгдэл байхгүй",
    "No notifications yet": "Одоохондоо мэдэгдэл байхгүй",
    "No results found": "Үр дүн олдсонгүй",
    "Search results": "Хайлтын үр дүн",
    "Search...": "Хайх...",
    "Search by name": "Нэрээр хайх",
    "Search by code": "Кодоор хайх",
    "Filter by region": "Бүсээр шүүх",
    "Filter by category": "Ангиллаар шүүх",
    "Filter by status": "Төлвөөр шүүх",
    "Filter by type": "Төрлөөр шүүх",
    "Clear filters": "Шүүлтүүр цэвэрлэх",
    "Clear all": "Бүгдийг цэвэрлэх",
    "Select all": "Бүгдийг сонгох",
    "Deselect all": "Сонголтыг арилгах",
    "Edit project": "Төслийг засах",
    "Delete project": "Төслийг устгах",
    "Archive project": "Төслийг архивлах",
    "Duplicate project": "Төслийг хуулбарлах",
    "Project archived": "Төсөл архивлагдлаа",
    "Project deleted": "Төсөл устгагдлаа",
    "Project updated": "Төсөл шинэчлэгдлээ",
    "Project created": "Төсөл үүсгэгдлээ",
    "Project saved": "Төсөл хадгалагдлаа",
    "Photo Quality Score": "Зургийн чанарын оноо",
    "Quality Score": "Чанарын оноо",
    "Risk score": "Эрсдэлийн оноо",
    "Score": "Оноо",
    "Total cost": "Нийт өртөг",
    "Total amount": "Нийт дүн",
    "Total quantity": "Нийт тоо хэмжээ",
    "Total positions": "Нийт байрлал",
    "Total items": "Нийт зүйл",
    "Item": "Зүйл",
    "Items": "Зүйлс",
    # Files / formats
    "Image files": "Зургийн файлууд",
    "PDF files": "PDF файлууд",
    "Excel files": "Excel файлууд",
    "All files": "Бүх файлууд",
    "File name": "Файлын нэр",
    "File size": "Файлын хэмжээ",
    "File type": "Файлын төрөл",
    "Download file": "Файл татах",
    "Upload file": "Файл байршуулах",
    "Upload files": "Файлуудыг байршуулах",
    "Upload complete": "Байршуулалт дууссан",
    "Upload failed": "Байршуулалт амжилтгүй",
    "Drag and drop": "Чирэх ба буулгах",
    "Drop file here": "Файлыг энд буулгана уу",
    "Drop files here": "Файлуудыг энд буулгана уу",
    "Browse files": "Файл сонгох",
    "Choose file": "Файл сонгох",
    "Choose files": "Файлууд сонгох",
    "Selected file": "Сонгосон файл",
    "Selected files": "Сонгосон файлууд",
    "No file selected": "Файл сонгогдоогүй",
    "Recent files": "Сүүлийн файлууд",
    "All categories": "Бүх ангилал",
    "All regions": "Бүх бүс",
    "All types": "Бүх төрөл",
    "All statuses": "Бүх төлөв",
    "By region": "Бүсээр",
    "By category": "Ангиллаар",
    "By status": "Төлвөөр",
    "By type": "Төрлөөр",
    "By date": "Огноогоор",
    "By name": "Нэрээр",
    # Errors
    "Something went wrong": "Алдаа гарлаа",
    "An error occurred": "Алдаа гарлаа",
    "Unknown error": "Үл мэдэгдэх алдаа",
    "Try refreshing the page": "Хуудсыг сэргээж үзнэ үү",
    "Check your connection": "Холболтоо шалгана уу",
    "Required field": "Шаардлагатай талбар",
    "Invalid input": "Буруу оролт",
    "Invalid value": "Буруу утга",
    "Invalid format": "Буруу формат",
    "Invalid email": "Буруу и-мэйл",
    "Invalid password": "Буруу нууц үг",
    "Field is required": "Талбар шаардлагатай",
    "This field is required": "Энэ талбар шаардлагатай",
    "Required fields missing": "Шаардлагатай талбарууд дутуу байна",
    "Too short": "Хэт богино",
    "Too long": "Хэт урт",
    "Out of range": "Хүрээнээс гадуур",
    "Must be a number": "Тоо байх ёстой",
    "Must be positive": "Эерэг байх ёстой",
}


# ---------------------------------------------------------------------------
# Token-level glossary for word-by-word translation.
# Applied after phrase-level lookup fails. Order matters for case sensitivity.
# ---------------------------------------------------------------------------
WORD_MAP: dict[str, str] = {
    # construction terms
    "construction": "барилгын",
    "construction's": "барилгын",
    "building": "барилга",
    "buildings": "барилгууд",
    "estimation": "тооцоолол",
    "estimate": "тооцоо",
    "estimates": "тооцоонууд",
    "estimated": "тооцоолсон",
    "estimating": "тооцоолох",
    "estimator": "тооцоологч",
    "estimators": "тооцоологчид",
    "cost": "өртөг",
    "costs": "өртгүүд",
    "costing": "өртөг бодох",
    "rate": "тариф",
    "rates": "тарифууд",
    "price": "үнэ",
    "prices": "үнэ",
    "pricing": "үнэ тогтоолт",
    "amount": "дүн",
    "amounts": "дүн",
    "total": "нийт",
    "totals": "нийт",
    "subtotal": "дэд дүн",
    "quantity": "тоо хэмжээ",
    "quantities": "тоо хэмжээ",
    "unit": "нэгж",
    "units": "нэгж",
    "currency": "валют",
    "currencies": "валютууд",
    "budget": "төсөв",
    "budgets": "төсвүүд",
    "budgeting": "төсвөлөлт",
    "project": "төсөл",
    "projects": "төслүүд",
    "tender": "тендер",
    "tenders": "тендерүүд",
    "tendering": "тендер",
    "bid": "санал",
    "bids": "саналууд",
    "bidding": "тендерийн санал",
    "bidder": "санал өгөгч",
    "bidders": "санал өгөгчид",
    "supplier": "нийлүүлэгч",
    "suppliers": "нийлүүлэгчид",
    "vendor": "нийлүүлэгч",
    "vendors": "нийлүүлэгчид",
    "subcontractor": "туслан гүйцэтгэгч",
    "subcontractors": "туслан гүйцэтгэгчид",
    "contractor": "гүйцэтгэгч",
    "contractors": "гүйцэтгэгчид",
    "contract": "гэрээ",
    "contracts": "гэрээнүүд",
    "client": "үйлчлүүлэгч",
    "clients": "үйлчлүүлэгчид",
    "risk": "эрсдэл",
    "risks": "эрсдэлүүд",
    "quality": "чанар",
    "safety": "аюулгүй байдал",
    "compliance": "дагалт",
    "document": "баримт бичиг",
    "documents": "баримт бичиг",
    "drawing": "зураг",
    "drawings": "зургууд",
    "model": "загвар",
    "models": "загварууд",
    "schedule": "хуваарь",
    "schedules": "хуваарь",
    "scheduling": "хуваарь гаргах",
    "activity": "үйл ажиллагаа",
    "activities": "үйл ажиллагаа",
    "task": "даалгавар",
    "tasks": "даалгавар",
    "report": "тайлан",
    "reports": "тайлан",
    "reporting": "тайлан гаргалт",
    "category": "ангилал",
    "categories": "ангилал",
    "section": "хэсэг",
    "sections": "хэсгүүд",
    "module": "модуль",
    "modules": "модулиуд",
    "marketplace": "маркетплейс",
    "catalog": "каталог",
    "catalogue": "каталог",
    "catalogs": "каталог",
    "catalogues": "каталог",
    "resource": "нөөц",
    "resources": "нөөц",
    "material": "материал",
    "materials": "материал",
    "equipment": "тоног төхөөрөмж",
    "labor": "хөдөлмөр",
    "labour": "хөдөлмөр",
    "worker": "ажилтан",
    "workers": "ажилтнууд",
    "team": "баг",
    "teams": "багууд",
    "user": "хэрэглэгч",
    "users": "хэрэглэгчид",
    "member": "гишүүн",
    "members": "гишүүд",
    "role": "үүрэг",
    "roles": "үүргүүд",
    "permission": "эрх",
    "permissions": "эрхүүд",
    "profile": "профайл",
    "account": "бүртгэл",
    "accounts": "бүртгэлүүд",
    "settings": "тохиргоо",
    "setting": "тохиргоо",
    "configuration": "тохиргоо",
    "config": "тохиргоо",
    "preferences": "тохиргоо",
    "options": "сонголтууд",
    "option": "сонголт",
    "language": "хэл",
    "languages": "хэлүүд",
    "theme": "загвар",
    "version": "хувилбар",
    "versions": "хувилбарууд",
    "update": "шинэчлэлт",
    "updates": "шинэчлэлтүүд",
    "upgrade": "сайжруулах",
    # nouns - elements
    "element": "элемент",
    "elements": "элементүүд",
    "position": "байрлал",
    "positions": "байрлалууд",
    "section": "хэсэг",
    "sections": "хэсгүүд",
    "group": "бүлэг",
    "groups": "бүлгүүд",
    "item": "зүйл",
    "items": "зүйлс",
    "row": "мөр",
    "rows": "мөрүүд",
    "column": "багана",
    "columns": "баганууд",
    "field": "талбар",
    "fields": "талбарууд",
    "value": "утга",
    "values": "утгууд",
    "name": "нэр",
    "names": "нэрс",
    "description": "тайлбар",
    "descriptions": "тайлбарууд",
    "title": "гарчиг",
    "subject": "сэдэв",
    "body": "агуулга",
    "content": "агуулга",
    "details": "дэлгэрэнгүй",
    "detail": "дэлгэрэнгүй",
    "summary": "хураангуй",
    "result": "үр дүн",
    "results": "үр дүн",
    "score": "оноо",
    "scores": "оноо",
    "metric": "үзүүлэлт",
    "metrics": "үзүүлэлтүүд",
    "level": "түвшин",
    "levels": "түвшинүүд",
    "phase": "үе шат",
    "phases": "үе шатууд",
    "stage": "шат",
    "stages": "шатууд",
    "step": "алхам",
    "steps": "алхамууд",
    # status
    "active": "идэвхтэй",
    "inactive": "идэвхгүй",
    "archived": "архивлагдсан",
    "deleted": "устгагдсан",
    "draft": "ноорог",
    "pending": "хүлээгдэж байна",
    "approved": "зөвшөөрөгдсөн",
    "rejected": "татгалзсан",
    "complete": "дууссан",
    "completed": "дууссан",
    "incomplete": "дуусаагүй",
    "open": "нээлттэй",
    "closed": "хаагдсан",
    "running": "ажиллаж байна",
    "stopped": "зогссон",
    "failed": "амжилтгүй",
    "success": "амжилт",
    "successful": "амжилттай",
    "successfully": "амжилттай",
    # verbs (lowercase, used in sentences)
    "save": "хадгалах",
    "saved": "хадгалагдсан",
    "cancel": "цуцлах",
    "delete": "устгах",
    "deleting": "устгаж байна",
    "edit": "засах",
    "editing": "засаж байна",
    "add": "нэмэх",
    "added": "нэмэгдсэн",
    "adding": "нэмж байна",
    "remove": "хасах",
    "removed": "хасагдсан",
    "removing": "хасаж байна",
    "create": "үүсгэх",
    "creating": "үүсгэж байна",
    "created": "үүсгэгдсэн",
    "open": "нээх",
    "opened": "нээгдсэн",
    "view": "үзэх",
    "viewing": "үзэж байна",
    "viewed": "үзсэн",
    "show": "харуулах",
    "hide": "нуух",
    "import": "импортлох",
    "imported": "импортлогдсон",
    "importing": "импортолж байна",
    "export": "экспортлох",
    "exported": "экспортлогдсон",
    "exporting": "экспортолж байна",
    "download": "татах",
    "downloaded": "татсан",
    "downloading": "татаж байна",
    "upload": "байршуулах",
    "uploaded": "байршуулсан",
    "uploading": "байршуулж байна",
    "submit": "илгээх",
    "submitted": "илгээсэн",
    "submitting": "илгээж байна",
    "send": "илгээх",
    "sent": "илгээсэн",
    "sending": "илгээж байна",
    "search": "хайх",
    "searched": "хайсан",
    "searching": "хайж байна",
    "filter": "шүүх",
    "filtered": "шүүсэн",
    "filtering": "шүүж байна",
    "refresh": "сэргээх",
    "refreshed": "сэргээсэн",
    "refreshing": "сэргээж байна",
    "reset": "дахин тохируулах",
    "apply": "хэрэглэх",
    "applied": "хэрэглэсэн",
    "applying": "хэрэглэж байна",
    "continue": "үргэлжлүүлэх",
    "back": "буцах",
    "next": "дараах",
    "previous": "өмнөх",
    "select": "сонгох",
    "selected": "сонгогдсон",
    "selecting": "сонгож байна",
    "choose": "сонгох",
    "confirm": "баталгаажуулах",
    "approve": "зөвшөөрөх",
    "reject": "татгалзах",
    "share": "хуваалцах",
    "shared": "хуваалцсан",
    "copy": "хуулах",
    "copied": "хуулсан",
    "duplicate": "хуулбарлах",
    "duplicated": "хуулбарлагдсан",
    "rename": "нэр өөрчлөх",
    "replace": "орлуулах",
    "move": "шилжүүлэх",
    "moved": "шилжсэн",
    "loading": "ачаалж байна",
    "loaded": "ачаалсан",
    "load": "ачаалах",
    "generate": "үүсгэх",
    "generated": "үүсгэгдсэн",
    "generating": "үүсгэж байна",
    "process": "боловсруулах",
    "processed": "боловсруулсан",
    "processing": "боловсруулж байна",
    "analyze": "шинжлэх",
    "analyzing": "шинжилж байна",
    "analyzed": "шинжилсэн",
    "validate": "баталгаажуулах",
    "validated": "баталгаажсан",
    "validating": "баталгаажуулж байна",
    "check": "шалгах",
    "checked": "шалгасан",
    "checking": "шалгаж байна",
    "connect": "холбогдох",
    "connected": "холбогдсон",
    "connecting": "холбогдож байна",
    "disconnect": "салгах",
    "disconnected": "салгасан",
    "configure": "тохируулах",
    "configured": "тохируулсан",
    "configuring": "тохируулж байна",
    "manage": "удирдах",
    "managed": "удирдсан",
    "managing": "удирдаж байна",
    "track": "хянах",
    "tracked": "хянасан",
    "tracking": "хянаж байна",
    "monitor": "хянах",
    "monitored": "хянасан",
    # adjectives / qualifiers
    "new": "шинэ",
    "old": "хуучин",
    "recent": "сүүлийн",
    "latest": "хамгийн сүүлийн",
    "current": "одоогийн",
    "all": "бүх",
    "any": "дурын",
    "every": "бүх",
    "each": "тус бүр",
    "none": "байхгүй",
    "other": "бусад",
    "another": "өөр",
    "more": "илүү",
    "less": "бага",
    "first": "эхний",
    "last": "сүүлийн",
    "default": "үндсэн",
    "custom": "захиалгат",
    "standard": "стандарт",
    "advanced": "дэвшилт",
    "basic": "үндсэн",
    "available": "боломжтой",
    "unavailable": "боломжгүй",
    "required": "шаардлагатай",
    "optional": "сонголтын",
    "recommended": "зөвлөмжтэй",
    "professional": "мэргэжлийн",
    "free": "үнэгүй",
    "paid": "төлбөртэй",
    "private": "хувийн",
    "public": "нийтийн",
    "shared": "хуваалцсан",
    "single": "ганц",
    "multiple": "олон",
    "many": "олон",
    "few": "цөөн",
    "several": "хэд хэдэн",
    "various": "янз бүрийн",
    "different": "ялгаатай",
    "same": "ижил",
    "similar": "төстэй",
    "valid": "хүчинтэй",
    "invalid": "хүчингүй",
    # connectives / function words
    "and": "ба",
    "or": "эсвэл",
    "the": "",
    "a": "",
    "an": "",
    "is": "нь",
    "are": "нь",
    "was": "байсан",
    "were": "байсан",
    "be": "байх",
    "been": "байсан",
    "being": "байх",
    "have": "байх",
    "has": "байх",
    "had": "байсан",
    "do": "хийх",
    "does": "хийдэг",
    "did": "хийсэн",
    "can": "чадна",
    "cannot": "чадахгүй",
    "could": "чадах",
    "will": "болно",
    "would": "болох",
    "should": "ёстой",
    "must": "ёстой",
    "may": "болно",
    "might": "болох",
    "from": "-аас",
    "to": "хүртэл",
    "in": "-д",
    "on": "дээр",
    "at": "-д",
    "by": "-аар",
    "for": "-д зориулсан",
    "with": "-тай",
    "without": "-гүй",
    "of": "-н",
    "about": "тухай",
    "into": "руу",
    "through": "дамжуулан",
    "during": "явцад",
    "before": "өмнө",
    "after": "дараа",
    "between": "хооронд",
    "as": "болгон",
    "than": "-аас",
    "while": "хооронд",
    "if": "хэрэв",
    "when": "хэзээ",
    "where": "хаана",
    "why": "яагаад",
    "how": "хэрхэн",
    "what": "юу",
    "which": "аль",
    "who": "хэн",
    "this": "энэ",
    "that": "тэр",
    "these": "эдгээр",
    "those": "тэдгээр",
    "your": "таны",
    "you": "та",
    "we": "бид",
    "our": "манай",
    "us": "биднийг",
    "they": "тэд",
    "their": "тэдний",
    "no": "үгүй",
    "yes": "тийм",
    "not": "биш",
    "only": "зөвхөн",
    "just": "зөвхөн",
    "also": "мөн",
    "too": "бас",
    "even": "хүртэл",
    "very": "маш",
    "really": "үнэхээр",
    "always": "үргэлж",
    "never": "хэзээ ч үгүй",
    "often": "ихэвчлэн",
    "sometimes": "заримдаа",
    "now": "одоо",
    "then": "тэгээд",
    "here": "энд",
    "there": "тэнд",
    "please": "та",
    "thanks": "баярлалаа",
    "thank you": "баярлалаа",
}


def title_case(word: str) -> str:
    return word[0].upper() + word[1:] if word else word


def translate_word_aware(text: str) -> str:
    """Translate while preserving case of first letter for nouns/verbs."""
    def replace(m: re.Match) -> str:
        w = m.group(0)
        lw = w.lower()
        if lw in WORD_MAP:
            t = WORD_MAP[lw]
            if not t:
                return ""
            if w[0].isupper() and len(w) > 1:
                return title_case(t)
            return t
        return w

    return re.sub(r"\b[A-Za-z']+\b", replace, text)


def cleanup(text: str) -> str:
    """Tidy up double spaces and stray punctuation."""
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+([.,;:!?])", r"\1", text)
    text = text.strip()
    return text


def translate_entry(text: str) -> str:
    """Translate one string to Mongolian Cyrillic, best-effort."""
    if not text:
        return text
    stripped = text.strip()
    # 1) Exact phrase match (case-sensitive)
    if stripped in PHRASES:
        return PHRASES[stripped]
    # Try with trailing punctuation removed
    m = re.match(r"^(.+?)([.!?:…]+)$", stripped)
    if m and m.group(1) in PHRASES:
        return PHRASES[m.group(1)] + m.group(2)
    # 2) Protect tokens
    protected, tokens = protect(text)
    # 3) Phrase match again on the protected form (sentinels)
    if protected.strip() in PHRASES:
        return restore(PHRASES[protected.strip()], tokens)
    # 4) Word-level translation
    translated = translate_word_aware(protected)
    # 5) Restore protected tokens
    translated = restore(translated, tokens)
    # 6) Cleanup
    translated = cleanup(translated)
    return translated


# ---------------------------------------------------------------------------
# Main: read mn.ts, replace only the untranslated values, write back.
# ---------------------------------------------------------------------------
def main() -> None:
    with open(UNTRANS_JSON, encoding="utf-8") as f:
        untranslated = json.load(f)

    mn_text = MN_PATH.read_text(encoding="utf-8")

    # Build new translations
    new_translations: dict[str, str] = {}
    for k, en_v in untranslated.items():
        new_translations[k] = translate_entry(en_v)

    # Now replace in mn.ts. Each line is of form:
    #   "key": "value",
    # We must replace ONLY the untranslated lines (key -> exact en value).
    # Use a pass-through line rewriter.
    out_lines: list[str] = []
    pat = re.compile(r'^(\s*)"((?:[^"\\]|\\.)+)"\s*:\s*"((?:[^"\\]|\\.)*)"(,?)\s*$')

    count_replaced = 0
    for line in mn_text.splitlines(keepends=True):
        stripped = line.rstrip("\n").rstrip("\r")
        m = pat.match(stripped)
        if m:
            indent, key, value, comma = m.group(1), m.group(2), m.group(3), m.group(4)
            if key in new_translations:
                # Replace value with translation
                new_val = new_translations[key]
                # Escape backslashes and quotes for JSON-string embedding
                # NOTE: en value used the same escaping; we mirror it.
                # Translator outputs raw text; escape \\ and " for output.
                esc = new_val.replace("\\", "\\\\").replace('"', '\\"')
                new_line = f'{indent}"{key}": "{esc}"{comma}\n'
                out_lines.append(new_line)
                count_replaced += 1
                continue
        out_lines.append(line)

    MN_PATH.write_text("".join(out_lines), encoding="utf-8")
    print(f"Replaced {count_replaced} entries in mn.ts")


if __name__ == "__main__":
    main()
