# -*- coding: utf-8 -*-
"""Pass 4: cleanup leaked English words in already-translated entries.

Instead of replacing whole values, we surgically substitute leaked English
words with their Mongolian equivalents WITHIN existing Mongolian translations.
This converts entries that are 80% Mongolian + 20% English (mixed) into
clean Mongolian.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_PATH = ROOT / "frontend" / "src" / "app" / "locales" / "en.ts"
MN_PATH = ROOT / "frontend" / "src" / "app" / "locales" / "mn.ts"


# Brand / acronym / technical terms - never touch
PROTECTED = {
    "OpenConstructionERP", "OpenEstimate", "OpenEstimator",
    "BIM", "IFC", "DWG", "DGN", "RVT", "DAE", "COLLADA", "Revit",
    "GAEB", "DIN", "NRM", "MasterFormat", "UniFormat", "Uniclass",
    "OmniClass", "SAP", "Procore", "Primavera", "PlanRadar",
    "PERT", "CPM", "CPI", "SPI", "MEP", "EVM", "ESG", "RFI", "NCR",
    "BAC", "EAC", "PV", "EV", "AC", "VAC", "SV", "CV", "ETC", "TCPI",
    "CWICR", "DDC", "Qdrant", "LanceDB", "BOQ", "BoQ", "JSON", "API",
    "OCR", "PDF", "CSV", "XML", "Excel", "Word", "VAT",
    "OpenAI", "Anthropic", "Claude", "Gemini", "Slack", "Telegram",
    "Microsoft", "Teams", "Google", "Outlook", "iCal", "Webhook",
    "ISO", "AACE", "AGPL", "GitHub", "LinkedIn", "Twitter",
    "BGE", "BAAI", "Monte", "Carlo", "Gantt", "DACH", "SQLite",
    "Parquet", "BKI", "BCIS", "RSMeans", "SNIP", "GESN", "STABU",
    "Birim", "Fiyat", "Sekisan", "SINAPI", "Computo", "DPGF", "KNR",
    "EUR", "USD", "MNT", "XAF", "BRL", "INR", "GBP", "JPY", "CNY",
    "TBD", "RFQ", "LLM", "QA", "CRM", "CAD", "AI", "WBS", "FX",
    "PRO", "STD", "HVAC", "BSt", "Pareto",
    "Ctrl", "Shift", "Enter", "Cmd", "Del", "Tab",
    "MB", "GB", "kg",
    "Hugging", "Face", "Yjs", "Vite", "GPT", "Berlin", "Munich",
    "Pos", "AU", "CA", "CN", "CZ", "ES", "FR", "IN", "KR", "PL",
    "UK", "US", "UAE", "NL", "JP", "IT", "RU", "BR", "TR", "DE",
    "BOQs", "RFIs", "NCRs", "Bau", "GmbH", "Nordic", "Imperial",
    "Q1", "Q2", "Q3", "Q4",
}


# Extended word-level glossary specifically targeting leaked words
WORDS: dict[str, str] = {
    # most common leaked
    "count": "тоо",
    "data": "өгөгдөл",
    "click": "дарах",
    "database": "өгөгдлийн сан",
    "databases": "өгөгдлийн сан",
    "file": "файл",
    "files": "файлууд",
    "code": "код",
    "match": "тааруулалт",
    "matches": "таарцууд",
    "matching": "тааруулж байна",
    "name": "нэр",
    "names": "нэрс",
    "pick": "сонгох",
    "picks": "сонголтууд",
    "picked": "сонгосон",
    "region": "бүс",
    "regions": "бүсүүд",
    "regional": "бүс нутгийн",
    "total": "нийт",
    "totals": "нийт",
    "start": "эхлэх",
    "starts": "эхэлдэг",
    "started": "эхэлсэн",
    "starting": "эхэлж байна",
    "again": "дахин",
    "change": "өөрчлөх",
    "changes": "өөрчлөлтүүд",
    "changed": "өөрчилсөн",
    "changing": "өөрчилж байна",
    "analysis": "шинжилгээ",
    "analyze": "шинжлэх",
    "analyzed": "шинжилсэн",
    "analyzing": "шинжилж байна",
    "auto": "автомат",
    "automatic": "автомат",
    "automatically": "автоматаар",
    "order": "захиалга",
    "orders": "захиалгууд",
    "ordered": "захиалсан",
    "existing": "одоо байгаа",
    "exists": "байгаа",
    "exist": "байх",
    "backup": "нөөц хуулбар",
    "backups": "нөөц хуулбарууд",
    "variant": "хувилбар",
    "variants": "хувилбарууд",
    "found": "олдсон",
    "find": "олох",
    "finding": "олох",
    "markup": "тэмдэглэгээ",
    "markups": "тэмдэглэгээ",
    "classification": "ангилал",
    "classifications": "ангилал",
    "classified": "ангилсан",
    "classify": "ангилах",
    "full": "бүрэн",
    "fully": "бүрэн",
    "source": "эх сурвалж",
    "sources": "эх сурвалжууд",
    "install": "суулгах",
    "installed": "суулгасан",
    "installation": "суулгац",
    "installer": "суулгагч",
    "type": "төрөл",
    "types": "төрлүүд",
    "photo": "зураг",
    "photos": "зургууд",
    "template": "загвар",
    "templates": "загварууд",
    "create": "үүсгэх",
    "creating": "үүсгэж байна",
    "creates": "үүсгэдэг",
    "created": "үүсгэгдсэн",
    "appear": "харагдах",
    "appears": "харагддаг",
    "appeared": "харагдсан",
    "appearing": "харагдаж байна",
    "label": "шошго",
    "labels": "шошго",
    "labeled": "шошголсон",
    "invoice": "нэхэмжлэх",
    "invoices": "нэхэмжлэх",
    "invoicing": "нэхэмжлэх",
    "requirement": "шаардлага",
    "requirements": "шаардлага",
    "text": "текст",
    "bill": "ажил жагсаалт",
    "large": "том",
    "larger": "илүү том",
    "link": "холбоос",
    "links": "холбоосууд",
    "linked": "холбосон",
    "linking": "холбож байна",
    "review": "хяналт",
    "reviews": "хяналтууд",
    "reviewed": "хянасан",
    "reviewing": "хянаж байна",
    "line": "мөр",
    "lines": "мөрүүд",
    "features": "боломжууд",
    "feature": "боломж",
    "describe": "тайлбарлах",
    "described": "тайлбарласан",
    "describes": "тайлбарладаг",
    "browse": "үзэх",
    "browser": "хөтөч",
    "below": "доор",
    "above": "дээр",
    "item": "зүйл",
    "items": "зүйлс",
    "session": "сесс",
    "sessions": "сессүүд",
    "lang": "хэл",
    "language": "хэл",
    "languages": "хэлүүд",
    "work": "ажил",
    "works": "ажилладаг",
    "working": "ажиллаж байна",
    "worked": "ажилласан",
    "over": "дээгүүр",
    "time": "цаг",
    "scope": "хүрээ",
    "built": "бүтсэн",
    "build": "бүтээх",
    "format": "формат",
    "formats": "форматууд",
    "switch": "солих",
    "switched": "сольсон",
    "switching": "сольж байна",
    "vector": "вектор",
    "vectors": "вектор",
    "tools": "хэрэгсэл",
    "tool": "хэрэгсэл",
    "provider": "үйлчилгээ үзүүлэгч",
    "providers": "үйлчилгээ үзүүлэгчид",
    "assembly": "угсралт",
    "assemblies": "угсралтууд",
    "build": "бүтээх",
    "comparison": "харьцуулалт",
    "compare": "харьцуулах",
    "compared": "харьцуулсан",
    "comparing": "харьцуулж байна",
    "converter": "хөрвүүлэгч",
    "converters": "хөрвүүлэгчид",
    "convert": "хөрвүүлэх",
    "conversion": "хөрвүүлэлт",
    "from": "-аас",
    "once": "удаа",
    "load": "ачаалах",
    "loaded": "ачаалсан",
    "loading": "ачаалж байна",
    "server": "сервер",
    "servers": "серверүүд",
    "note": "тэмдэглэл",
    "notes": "тэмдэглэл",
    "snapshot": "хувилбар",
    "snapshots": "хувилбарууд",
    "project": "төсөл",
    "projects": "төслүүд",
    "report": "тайлан",
    "reports": "тайлан",
    "reporting": "тайлан гаргалт",
    "bundle": "багц",
    "bundles": "багцууд",
    "across": "хооронд",
    "missing": "дутуу",
    "miss": "алдах",
    "missed": "алдсан",
    "need": "хэрэгцээ",
    "needs": "хэрэгтэй",
    "needed": "шаардлагатай",
    "breakdown": "задаргаа",
    "extract": "гаргаж авах",
    "extracted": "гаргаж авсан",
    "extracts": "гаргаж авдаг",
    "extracting": "гаргаж авч байна",
    "extraction": "гаргалт",
    "container": "контейнер",
    "containers": "контейнерүүд",
    "actual": "бодит",
    "actually": "үнэндээ",
    "variance": "хэлбэлзэл",
    "submittal": "илгээлт",
    "submittals": "илгээлт",
    "management": "удирдлага",
    "manage": "удирдах",
    "managed": "удирдсан",
    "managing": "удирдаж байна",
    "manager": "менежер",
    "managers": "менежерүүд",
    "critical": "чухал",
    "side": "тал",
    "access": "хандалт",
    "paste": "буулгах",
    "pasted": "буулгасан",
    "filters": "шүүлтүүр",
    "filter": "шүүх",
    "mode": "горим",
    "modes": "горимууд",
    "list": "жагсаалт",
    "lists": "жагсаалт",
    "listing": "жагсаалт",
    "ready": "бэлэн",
    "position": "байрлал",
    "positions": "байрлалууд",
    "test": "тест",
    "tests": "тестүүд",
    "testing": "тестлэж байна",
    "field": "талбар",
    "fields": "талбарууд",
    "value": "утга",
    "values": "утгууд",
    "rate": "тариф",
    "rates": "тарифууд",
    "rating": "үнэлгээ",
    "ratings": "үнэлгээ",
    "rated": "үнэлгээтэй",
    "view": "үзэх",
    "views": "харагдац",
    "viewing": "үзэж байна",
    "viewed": "үзсэн",
    "edit": "засах",
    "edited": "зассан",
    "editing": "засаж байна",
    "save": "хадгалах",
    "saved": "хадгалагдсан",
    "saving": "хадгалж байна",
    "saves": "хадгалдаг",
    "delete": "устгах",
    "deleted": "устгасан",
    "deletes": "устгадаг",
    "deleting": "устгаж байна",
    "add": "нэмэх",
    "added": "нэмэгдсэн",
    "adding": "нэмж байна",
    "remove": "хасах",
    "removed": "хасагдсан",
    "removing": "хасаж байна",
    "update": "шинэчлэх",
    "updates": "шинэчлэлтүүд",
    "updated": "шинэчлэгдсэн",
    "updating": "шинэчилж байна",
    "open": "нээх",
    "opened": "нээгдсэн",
    "opening": "нээж байна",
    "close": "хаах",
    "closed": "хаагдсан",
    "closing": "хааж байна",
    "show": "харуулах",
    "shows": "харуулдаг",
    "showed": "харуулсан",
    "showing": "харуулж байна",
    "hide": "нуух",
    "hidden": "нуугдсан",
    "hiding": "нуугдаж байна",
    "search": "хайх",
    "searched": "хайсан",
    "searches": "хайлтууд",
    "searching": "хайж байна",
    "select": "сонгох",
    "selected": "сонгогдсон",
    "selecting": "сонгож байна",
    "selection": "сонголт",
    "selections": "сонголтууд",
    "choose": "сонгох",
    "chose": "сонгосон",
    "chosen": "сонгосон",
    "choosing": "сонгож байна",
    "import": "импортлох",
    "imported": "импортлогдсон",
    "importing": "импортолж байна",
    "imports": "импортууд",
    "export": "экспортлох",
    "exported": "экспортлогдсон",
    "exporting": "экспортолж байна",
    "exports": "экспортууд",
    "download": "татах",
    "downloaded": "татсан",
    "downloading": "татаж байна",
    "downloads": "татацууд",
    "upload": "байршуулах",
    "uploaded": "байршуулсан",
    "uploading": "байршуулж байна",
    "uploads": "байршуулалтууд",
    "send": "илгээх",
    "sent": "илгээсэн",
    "sending": "илгээж байна",
    "submit": "илгээх",
    "submitted": "илгээсэн",
    "submitting": "илгээж байна",
    "valid": "хүчинтэй",
    "validate": "баталгаажуулах",
    "validation": "баталгаажуулалт",
    "validated": "баталгаажсан",
    "validating": "баталгаажуулж байна",
    "invalid": "хүчингүй",
    "verify": "шалгах",
    "verified": "баталгаажсан",
    "verifying": "шалгаж байна",
    "verification": "баталгаажуулалт",
    "process": "процесс",
    "processes": "процессууд",
    "processed": "боловсруулсан",
    "processing": "боловсруулж байна",
    "generate": "үүсгэх",
    "generated": "үүсгэгдсэн",
    "generating": "үүсгэж байна",
    "generation": "үүсгэлт",
    "configure": "тохируулах",
    "configured": "тохируулсан",
    "configuring": "тохируулж байна",
    "configuration": "тохиргоо",
    "configurations": "тохиргоо",
    "manage": "удирдах",
    "managed": "удирдсан",
    "managing": "удирдаж байна",
    "user": "хэрэглэгч",
    "users": "хэрэглэгчид",
    "users": "хэрэглэгчид",
    "members": "гишүүд",
    "member": "гишүүн",
    "team": "баг",
    "teams": "багууд",
    "owner": "эзэмшигч",
    "owners": "эзэмшигчид",
    "list": "жагсаалт",
    "lists": "жагсаалт",
    "page": "хуудас",
    "pages": "хуудсууд",
    "section": "хэсэг",
    "sections": "хэсгүүд",
    "tab": "таб",
    "tabs": "табууд",
    "row": "мөр",
    "rows": "мөрүүд",
    "column": "багана",
    "columns": "баганууд",
    "field": "талбар",
    "fields": "талбарууд",
    "filter": "шүүх",
    "filters": "шүүлтүүр",
    "sort": "эрэмбэлэх",
    "sorted": "эрэмбэлсэн",
    "sorting": "эрэмбэлж байна",
    "group": "бүлэг",
    "groups": "бүлгүүд",
    "grouped": "бүлэглэсэн",
    "grouping": "бүлэглэж байна",
    "category": "ангилал",
    "categories": "ангилал",
    "tag": "шошго",
    "tags": "шошго",
    "tagged": "шошготой",
    "tagging": "шошго өгөх",
    "comment": "сэтгэгдэл",
    "comments": "сэтгэгдэл",
    "commented": "сэтгэгдэл бичсэн",
    "commenting": "сэтгэгдэл бичиж байна",
    "title": "гарчиг",
    "titles": "гарчигууд",
    "subject": "сэдэв",
    "subjects": "сэдвүүд",
    "description": "тайлбар",
    "descriptions": "тайлбарууд",
    "details": "дэлгэрэнгүй",
    "detail": "дэлгэрэнгүй",
    "summary": "хураангуй",
    "summaries": "хураангуй",
    "info": "мэдээлэл",
    "information": "мэдээлэл",
    "infos": "мэдээллүүд",
    "more": "илүү",
    "less": "бага",
    "much": "их",
    "many": "олон",
    "few": "цөөн",
    "any": "ямар нэгэн",
    "some": "зарим",
    "all": "бүх",
    "every": "бүх",
    "each": "тус бүр",
    "no": "үгүй",
    "none": "байхгүй",
    "other": "бусад",
    "others": "бусад",
    "another": "өөр",
    "these": "эдгээр",
    "those": "тэдгээр",
    "this": "энэ",
    "that": "тэр",
    "here": "энд",
    "there": "тэнд",
    "when": "хэзээ",
    "where": "хаана",
    "what": "юу",
    "which": "аль",
    "who": "хэн",
    "whose": "хэний",
    "why": "яагаад",
    "how": "хэрхэн",
    "now": "одоо",
    "then": "тэгэхэд",
    "before": "өмнө",
    "after": "дараа",
    "during": "явцад",
    "while": "хооронд",
    "between": "хооронд",
    "among": "дунд",
    "with": "-тай",
    "without": "-гүй",
    "within": "дотор",
    "into": "руу",
    "onto": "дээр",
    "upon": "дээр",
    "through": "дамжуулан",
    "across": "хооронд",
    "around": "эргэн тойронд",
    "near": "ойролцоо",
    "far": "хол",
    "today": "өнөөдөр",
    "yesterday": "өчигдөр",
    "tomorrow": "маргааш",
    "soon": "удахгүй",
    "later": "дараа нь",
    "early": "эрт",
    "late": "оройтсон",
    "yes": "тийм",
    "true": "үнэн",
    "false": "худал",
    "right": "зөв",
    "wrong": "буруу",
    "good": "сайн",
    "bad": "муу",
    "best": "хамгийн сайн",
    "worst": "хамгийн муу",
    "first": "эхний",
    "last": "сүүлийн",
    "next": "дараах",
    "previous": "өмнөх",
    "current": "одоогийн",
    "old": "хуучин",
    "new": "шинэ",
    "newer": "илүү шинэ",
    "older": "илүү хуучин",
    "newest": "хамгийн шинэ",
    "oldest": "хамгийн хуучин",
    "high": "өндөр",
    "low": "бага",
    "higher": "илүү өндөр",
    "lower": "илүү бага",
    "highest": "хамгийн өндөр",
    "lowest": "хамгийн бага",
    "small": "жижиг",
    "big": "том",
    "smaller": "илүү жижиг",
    "bigger": "илүү том",
    "fast": "хурдан",
    "slow": "удаан",
    "faster": "илүү хурдан",
    "slower": "илүү удаан",
    "easy": "хялбар",
    "hard": "хүнд",
    "simple": "энгийн",
    "complex": "нийлмэл",
    "complicated": "нарийн төвөгтэй",
    "important": "чухал",
    "necessary": "зайлшгүй шаардлагатай",
    "useful": "хэрэгцээтэй",
    "useless": "хэрэггүй",
    "available": "боломжтой",
    "unavailable": "боломжгүй",
    "active": "идэвхтэй",
    "inactive": "идэвхгүй",
    "enable": "идэвхжүүлэх",
    "enabled": "идэвхтэй",
    "enabling": "идэвхжүүлж байна",
    "disable": "идэвхгүй болгох",
    "disabled": "идэвхгүй",
    "disabling": "идэвхгүй болгож байна",
    "allow": "зөвшөөрөх",
    "allowed": "зөвшөөрсөн",
    "allowing": "зөвшөөрч байна",
    "deny": "хориглох",
    "denied": "хориглосон",
    "denying": "хориглож байна",
    "permission": "эрх",
    "permissions": "эрхүүд",
    "role": "үүрэг",
    "roles": "үүргүүд",
    "right": "эрх",
    "rights": "эрхүүд",
    "feature": "боломж",
    "features": "боломжууд",
    "function": "функц",
    "functions": "функцүүд",
    "method": "арга",
    "methods": "аргууд",
    "way": "арга",
    "ways": "аргууд",
    "step": "алхам",
    "steps": "алхамууд",
    "phase": "үе шат",
    "phases": "үе шатууд",
    "stage": "шат",
    "stages": "шатууд",
    "level": "түвшин",
    "levels": "түвшнүүд",
    "tier": "түвшин",
    "tiers": "түвшнүүд",
    "rank": "байр",
    "ranks": "байрууд",
    "score": "оноо",
    "scores": "оноо",
    "result": "үр дүн",
    "results": "үр дүн",
    "outcome": "үр дүн",
    "outcomes": "үр дүн",
    "answer": "хариулт",
    "answers": "хариултууд",
    "question": "асуулт",
    "questions": "асуултууд",
    "issue": "асуудал",
    "issues": "асуудлууд",
    "problem": "асуудал",
    "problems": "асуудлууд",
    "error": "алдаа",
    "errors": "алдаанууд",
    "warning": "анхааруулга",
    "warnings": "анхааруулга",
    "alert": "анхааруулга",
    "alerts": "анхааруулга",
    "message": "зурвас",
    "messages": "зурвасууд",
    "log": "бүртгэл",
    "logs": "бүртгэл",
    "logged": "бүртгэгдсэн",
    "logging": "бүртгэж байна",
    "history": "түүх",
    "histories": "түүх",
    "snapshot": "хувилбар",
    "snapshots": "хувилбарууд",
    "version": "хувилбар",
    "versions": "хувилбарууд",
    "release": "хувилбар",
    "releases": "хувилбарууд",
    "released": "гарсан",
    "releasing": "гарч байна",
    "page": "хуудас",
    "pages": "хуудсууд",
    "screen": "дэлгэц",
    "screens": "дэлгэцүүд",
    "view": "харагдац",
    "views": "харагдац",
    "panel": "самбар",
    "panels": "самбар",
    "dialog": "цонх",
    "dialogs": "цонхнууд",
    "window": "цонх",
    "windows": "цонхнууд",
    "modal": "модаль",
    "modals": "модаль",
    "popup": "попап",
    "popups": "попап",
    "tooltip": "зөвлөмж",
    "tooltips": "зөвлөмжүүд",
    "form": "маягт",
    "forms": "маягтууд",
    "button": "товч",
    "buttons": "товчнууд",
    "icon": "дүрс",
    "icons": "дүрс",
    "menu": "цэс",
    "menus": "цэс",
    "drawing": "зураг",
    "drawings": "зургууд",
    "draw": "зурах",
    "drawn": "зурсан",
    "drawing": "зураг",
    "image": "зураг",
    "images": "зургууд",
    "model": "загвар",
    "models": "загварууд",
    "element": "элемент",
    "elements": "элементүүд",
    "object": "объект",
    "objects": "объектууд",
    "thing": "зүйл",
    "things": "зүйлс",
    "stuff": "зүйл",
    "scope": "хүрээ",
    "scopes": "хүрээнүүд",
    "context": "контекст",
    "contexts": "контекстууд",
    "limit": "хязгаар",
    "limits": "хязгаарууд",
    "limited": "хязгаарлагдсан",
    "limiting": "хязгаарлаж байна",
    "max": "дээд",
    "min": "доод",
    "maximum": "дээд",
    "minimum": "доод",
    "size": "хэмжээ",
    "sizes": "хэмжээнүүд",
    "length": "урт",
    "lengths": "урт",
    "width": "өргөн",
    "widths": "өргөн",
    "height": "өндөр",
    "heights": "өндөр",
    "weight": "жин",
    "weights": "жин",
    "depth": "гүн",
    "depths": "гүн",
    "area": "талбай",
    "areas": "талбайнууд",
    "volume": "эзэлхүүн",
    "volumes": "эзэлхүүн",
    "amount": "дүн",
    "amounts": "дүн",
    "number": "тоо",
    "numbers": "тоонууд",
    "quantity": "тоо хэмжээ",
    "quantities": "тоо хэмжээ",
    "unit": "нэгж",
    "units": "нэгж",
    "metric": "үзүүлэлт",
    "metrics": "үзүүлэлт",
    "measure": "хэмжих",
    "measured": "хэмжсэн",
    "measuring": "хэмжиж байна",
    "measurement": "хэмжилт",
    "measurements": "хэмжилтүүд",
    "value": "утга",
    "values": "утгууд",
    "default": "үндсэн",
    "defaults": "үндсэн утгууд",
    "custom": "захиалгат",
    "preset": "урьдчилан тохируулсан",
    "presets": "урьдчилан тохиргоо",
    "preset": "урьдчилан тохируулсан",
    "preference": "тохиргоо",
    "preferences": "тохиргоо",
    "settings": "тохиргоо",
    "setting": "тохиргоо",
    "config": "тохиргоо",
    "option": "сонголт",
    "options": "сонголтууд",
    "choice": "сонголт",
    "choices": "сонголтууд",
    "rule": "дүрэм",
    "rules": "дүрэм",
    "policy": "бодлого",
    "policies": "бодлогууд",
    "standard": "стандарт",
    "standards": "стандартууд",
    "compliance": "дагалт",
    "compliant": "дагасан",
    "noncompliant": "дагаагүй",
    "approve": "зөвшөөрөх",
    "approved": "зөвшөөрөгдсөн",
    "approving": "зөвшөөрч байна",
    "approval": "зөвшөөрөл",
    "approvals": "зөвшөөрлүүд",
    "reject": "татгалзах",
    "rejected": "татгалзсан",
    "rejecting": "татгалзаж байна",
    "rejection": "татгалзал",
    "rejections": "татгалзлууд",
    "confirm": "баталгаажуулах",
    "confirmed": "баталгаажсан",
    "confirming": "баталгаажуулж байна",
    "confirmation": "баталгаажуулалт",
    "confirmations": "баталгаажуулалтууд",
    "cancel": "цуцлах",
    "cancelled": "цуцалсан",
    "canceling": "цуцалж байна",
    "cancellation": "цуцлалт",
    "complete": "дуусгах",
    "completed": "дууссан",
    "completing": "дуусгаж байна",
    "completion": "дуусгал",
    "finish": "дуусгах",
    "finished": "дууссан",
    "finishing": "дуусгаж байна",
    "end": "дуусгах",
    "ended": "дууссан",
    "ending": "дуусаж байна",
    "endpoint": "endpoint",
    "endpoints": "endpoint-үүд",
    "begin": "эхлэх",
    "began": "эхэлсэн",
    "begun": "эхэлсэн",
    "beginning": "эхлэл",
    "stop": "зогсоох",
    "stopped": "зогссон",
    "stopping": "зогсоож байна",
    "pause": "зогсоох",
    "paused": "зогссон",
    "pausing": "зогсоож байна",
    "resume": "үргэлжлүүлэх",
    "resumed": "үргэлжилсэн",
    "resuming": "үргэлжлүүлж байна",
    "wait": "хүлээх",
    "waited": "хүлээсэн",
    "waiting": "хүлээж байна",
    "ready": "бэлэн",
    "prepare": "бэлдэх",
    "prepared": "бэлдсэн",
    "preparing": "бэлдэж байна",
    "preparation": "бэлтгэл",
    "setup": "тохиргоо",
    "setups": "тохиргоо",
    "init": "инициаци",
    "initialize": "инициалчлах",
    "initialized": "инициалчлагдсан",
    "initializing": "инициалчилж байна",
    "boot": "ачаалах",
    "booted": "ачаалагдсан",
    "booting": "ачаалж байна",
    "shutdown": "унтраах",
    "shutting": "унтраах",
    "exit": "гарах",
    "exited": "гарсан",
    "exiting": "гарч байна",
    "quit": "гарах",
    "logout": "гарах",
    "login": "нэвтрэх",
    "signin": "нэвтрэх",
    "signup": "бүртгүүлэх",
    "signout": "гарах",
    "register": "бүртгүүлэх",
    "registered": "бүртгэгдсэн",
    "registering": "бүртгэж байна",
    "registration": "бүртгэл",
    "subscribe": "захиалах",
    "subscribed": "захиалсан",
    "subscribing": "захиалж байна",
    "subscription": "захиалга",
    "subscriptions": "захиалгууд",
    "license": "лиценз",
    "licenses": "лиценз",
    "licensed": "лицензтэй",
    "licensing": "лиценз олгох",
    "free": "үнэгүй",
    "freely": "үнэгүй",
    "paid": "төлбөртэй",
    "trial": "туршилт",
    "premium": "премиум",
    "pro": "PRO",
    "professional": "мэргэжлийн",
    "basic": "үндсэн",
    "advanced": "дэвшилт",
    "expert": "мэргэжилтэн",
    "experts": "мэргэжилтнүүд",
    "beginner": "анхан шатны",
    "intermediate": "дунд шатны",
    "secure": "аюулгүй",
    "secured": "хамгаалсан",
    "security": "аюулгүй байдал",
    "privacy": "хувийн нууц",
    "private": "хувийн",
    "public": "нийтийн",
    "publish": "нийтлэх",
    "published": "нийтлэгдсэн",
    "publishing": "нийтэлж байна",
    "publication": "хэвлэл",
    "publications": "хэвлэлүүд",
    "share": "хуваалцах",
    "shared": "хуваалцсан",
    "sharing": "хуваалцаж байна",
    "send": "илгээх",
    "sent": "илгээсэн",
    "sending": "илгээж байна",
    "receive": "хүлээн авах",
    "received": "хүлээн авсан",
    "receiving": "хүлээн авч байна",
    "client": "үйлчлүүлэгч",
    "clients": "үйлчлүүлэгчид",
    "customer": "үйлчлүүлэгч",
    "customers": "үйлчлүүлэгчид",
    "supplier": "нийлүүлэгч",
    "suppliers": "нийлүүлэгчид",
    "vendor": "нийлүүлэгч",
    "vendors": "нийлүүлэгчид",
    "partner": "хамтрагч",
    "partners": "хамтрагчид",
    "stakeholder": "оролцогч",
    "stakeholders": "оролцогчид",
    "contact": "холбоо",
    "contacts": "холбоо",
    "company": "компани",
    "companies": "компаниуд",
    "organization": "байгууллага",
    "organizations": "байгууллагууд",
    "department": "хэлтэс",
    "departments": "хэлтэсүүд",
    "office": "оффис",
    "offices": "оффисууд",
    "branch": "салбар",
    "branches": "салбарууд",
    "location": "байршил",
    "locations": "байршлууд",
    "place": "газар",
    "places": "газрууд",
    "address": "хаяг",
    "addresses": "хаягууд",
    "country": "улс",
    "countries": "улсууд",
    "city": "хот",
    "cities": "хотууд",
    "state": "муж",
    "states": "мужууд",
    "currency": "валют",
    "currencies": "валютууд",
    "money": "мөнгө",
    "cash": "бэлэн мөнгө",
    "payment": "төлбөр",
    "payments": "төлбөр",
    "pay": "төлөх",
    "paid": "төлсөн",
    "paying": "төлж байна",
    "fee": "хураамж",
    "fees": "хураамжууд",
    "tax": "татвар",
    "taxes": "татварууд",
    "discount": "хөнгөлөлт",
    "discounts": "хөнгөлөлтүүд",
    "income": "орлого",
    "expense": "зардал",
    "expenses": "зардлууд",
    "spend": "зарцуулах",
    "spent": "зарцуулсан",
    "spending": "зарцуулалт",
    "earn": "олох",
    "earned": "олсон",
    "earning": "орлого",
    "earnings": "орлого",
    "profit": "ашиг",
    "profits": "ашиг",
    "loss": "алдагдал",
    "losses": "алдагдлууд",
    "revenue": "орлого",
    "revenues": "орлого",
    "budget": "төсөв",
    "budgets": "төсвүүд",
    "forecast": "урьдчилсан таамаг",
    "forecasts": "урьдчилсан таамгууд",
    "projection": "урьдчилсан тооцоо",
    "projections": "урьдчилсан тооцоо",
    "estimate": "тооцоо",
    "estimates": "тооцоонууд",
    "estimated": "тооцоолсон",
    "estimating": "тооцоолж байна",
    "estimation": "тооцоолол",
    "calculation": "тооцоолол",
    "calculations": "тооцоолол",
    "calculate": "тооцоолох",
    "calculated": "тооцоолсон",
    "calculating": "тооцоолж байна",
    "compute": "тооцоолох",
    "computed": "тооцоолсон",
    "computing": "тооцоолж байна",
    "tender": "тендер",
    "tenders": "тендерүүд",
    "tendering": "тендер",
    "bid": "санал",
    "bids": "саналууд",
    "bidder": "санал өгөгч",
    "bidders": "санал өгөгчид",
    "bidding": "тендерийн санал",
    "purchase": "худалдан авалт",
    "purchases": "худалдан авалт",
    "purchased": "худалдан авсан",
    "purchasing": "худалдан авч байна",
    "procurement": "худалдан авалт",
    "supply": "нийлүүлэлт",
    "supplies": "нийлүүлэлт",
    "supplied": "нийлүүлсэн",
    "supplying": "нийлүүлж байна",
    "deliver": "хүргэх",
    "delivered": "хүргэсэн",
    "delivering": "хүргэж байна",
    "delivery": "хүргэлт",
    "deliveries": "хүргэлтүүд",
    "shipping": "тээвэрлэлт",
    "ship": "ачих",
    "shipped": "ачсан",
    "shipping": "тээвэрлэлт",
    "warehouse": "агуулах",
    "warehouses": "агуулахууд",
    "inventory": "бараа материал",
    "stock": "нөөц",
    "stocks": "нөөц",
    "construction": "барилгын",
    "constructing": "барих",
    "constructed": "барьсан",
    "build": "барих",
    "built": "барьсан",
    "building": "барилга",
    "buildings": "барилгууд",
    "design": "дизайн",
    "designs": "дизайн",
    "designed": "зохиосон",
    "designing": "зохиож байна",
    "designer": "дизайнер",
    "designers": "дизайнерууд",
    "engineer": "инженер",
    "engineers": "инженерүүд",
    "engineering": "инженерчлэл",
    "architect": "архитектор",
    "architects": "архитекторууд",
    "architecture": "архитектур",
    "contractor": "гүйцэтгэгч",
    "contractors": "гүйцэтгэгчид",
    "subcontractor": "туслан гүйцэтгэгч",
    "subcontractors": "туслан гүйцэтгэгчид",
    "worker": "ажилтан",
    "workers": "ажилчид",
    "labor": "хөдөлмөр",
    "labour": "хөдөлмөр",
    "site": "талбай",
    "sites": "талбайнууд",
    "field": "талбар",
    "fields": "талбарууд",
    "floor": "давхар",
    "floors": "давхрууд",
    "storey": "давхар",
    "storeys": "давхрууд",
    "story": "давхар",
    "stories": "давхрууд",
    "level": "түвшин",
    "levels": "түвшинүүд",
    "zone": "бүс",
    "zones": "бүсүүд",
    "room": "өрөө",
    "rooms": "өрөөнүүд",
    "wall": "хана",
    "walls": "ханууд",
    "door": "хаалга",
    "doors": "хаалгууд",
    "window": "цонх",
    "windows": "цонхнууд",
    "roof": "дээвэр",
    "roofs": "дээврүүд",
    "ceiling": "тааз",
    "ceilings": "тааз",
    "concrete": "бетон",
    "steel": "ган",
    "wood": "мод",
    "brick": "тоосго",
    "bricks": "тоосгууд",
    "tile": "плита",
    "tiles": "плитүүд",
    "paint": "будаг",
    "paints": "будгууд",
    "painted": "будсан",
    "painting": "будаж байна",
    "finish": "өнгөлгөө",
    "finishes": "өнгөлгөө",
    "finishing": "өнгөлгөө",
    "structural": "бүтцийн",
    "structure": "бүтэц",
    "structures": "бүтцүүд",
    "foundation": "суурь",
    "foundations": "суурьнууд",
    "column": "багана",
    "columns": "баганууд",
    "beam": "цацраг",
    "beams": "цацрагууд",
    "slab": "хавтгай",
    "slabs": "хавтгайнууд",
    "rebar": "арматур",
    "reinforcement": "армат",
    "reinforced": "армопэлсэн",
    "schedule": "хуваарь",
    "scheduled": "хуваарьласан",
    "scheduling": "хуваарь гаргалт",
    "schedules": "хуваарь",
    "calendar": "календарь",
    "calendars": "календарь",
    "task": "даалгавар",
    "tasks": "даалгавар",
    "tasked": "даалгавартай",
    "tasking": "даалгавар өгөх",
    "activity": "үйл ажиллагаа",
    "activities": "үйл ажиллагаа",
    "event": "үйл явдал",
    "events": "үйл явдал",
    "meeting": "уулзалт",
    "meetings": "уулзалт",
    "appointment": "товлолт",
    "appointments": "товлолтууд",
    "deadline": "эцсийн хугацаа",
    "deadlines": "эцсийн хугацаа",
    "due": "хугацаа",
    "milestone": "чухал үе",
    "milestones": "чухал үе",
    "phase": "үе шат",
    "phases": "үе шатууд",
    "duration": "үргэлжлэх хугацаа",
    "durations": "үргэлжлэх хугацаа",
    "start": "эхлэх",
    "started": "эхэлсэн",
    "starting": "эхэлж байна",
    "begin": "эхлэх",
    "began": "эхэлсэн",
    "end": "дуусгах",
    "ended": "дууссан",
    "ending": "дуусаж байна",
    "progress": "явц",
    "progressed": "явсан",
    "progressing": "явж байна",
    "complete": "дуусгах",
    "completed": "дууссан",
    "completing": "дуусгаж байна",
    "completion": "дуусгал",
    "finish": "дуусгах",
    "finished": "дууссан",
    "finishing": "дуусгаж байна",
    "quality": "чанар",
    "qualities": "чанаруудd",
    "safety": "аюулгүй байдал",
    "safe": "аюулгүй",
    "unsafe": "аюултай",
    "hazard": "аюул",
    "hazards": "аюулууд",
    "incident": "тохиолдол",
    "incidents": "тохиолдлууд",
    "accident": "осол",
    "accidents": "осол",
    "injury": "гэмтэл",
    "injuries": "гэмтэл",
    "risk": "эрсдэл",
    "risks": "эрсдэл",
    "risky": "эрсдэлтэй",
    "issue": "асуудал",
    "issues": "асуудлууд",
    "defect": "гэмтэл",
    "defects": "гэмтэлүүд",
    "ticket": "тасалбар",
    "tickets": "тасалбарууд",
    "punch": "punch",
    "checklist": "шалгах хуудас",
    "checklists": "шалгах хуудсууд",
    "inspection": "шалгалт",
    "inspections": "шалгалт",
    "inspector": "шалгагч",
    "inspectors": "шалгагчид",
    "audit": "аудит",
    "audits": "аудит",
    "auditor": "аудитор",
    "auditors": "аудиторууд",
    "report": "тайлан",
    "reports": "тайлан",
    "reported": "тайлагнасан",
    "reporting": "тайлан гаргалт",
    "reporter": "тайлагнагч",
    "approve": "зөвшөөрөх",
    "approved": "зөвшөөрөгдсөн",
    "rejection": "татгалзал",
    "rejected": "татгалзсан",
    "comment": "сэтгэгдэл",
    "comments": "сэтгэгдэл",
    "annotation": "тайлбар",
    "annotations": "тайлбар",
    "remark": "тэмдэглэгээ",
    "remarks": "тэмдэглэгээ",
    "version": "хувилбар",
    "versions": "хувилбарууд",
    "revision": "хувилбар",
    "revisions": "хувилбарууд",
    "history": "түүх",
    "histories": "түүх",
    "log": "бүртгэл",
    "logs": "бүртгэл",
    "audit": "аудит",
    "trail": "ул мөр",
    "trails": "ул мөр",
    "track": "хянах",
    "tracked": "хянасан",
    "tracking": "хянаж байна",
    "tracker": "хянагч",
    "trackers": "хянагчид",
    "monitor": "хянах",
    "monitored": "хянасан",
    "monitoring": "хянаж байна",
    "watch": "ажиглах",
    "watched": "ажигласан",
    "watching": "ажиглаж байна",
    "view": "үзэх",
    "viewed": "үзсэн",
    "viewing": "үзэж байна",
    "viewer": "үзэгч",
    "viewers": "үзэгчид",
    "open": "нээх",
    "opened": "нээгдсэн",
    "opening": "нээж байна",
    "close": "хаах",
    "closed": "хаагдсан",
    "closing": "хааж байна",
    "show": "харуулах",
    "shown": "харагдсан",
    "showing": "харуулж байна",
    "hide": "нуух",
    "hidden": "нуугдсан",
    "hiding": "нуугдаж байна",
    "display": "харуулах",
    "displayed": "харагдсан",
    "displaying": "харуулж байна",
    "render": "зурах",
    "rendered": "зурсан",
    "rendering": "зурж байна",
    "draw": "зурах",
    "drawn": "зурсан",
    "drawing": "зурж байна",
    "paint": "будах",
    "painted": "будсан",
    "painting": "будаж байна",
    "edit": "засах",
    "edited": "зассан",
    "editing": "засаж байна",
    "editor": "редактор",
    "editors": "редакторууд",
    "modify": "өөрчлөх",
    "modified": "өөрчилсөн",
    "modifying": "өөрчилж байна",
    "modification": "өөрчлөлт",
    "modifications": "өөрчлөлтүүд",
    "change": "өөрчлөх",
    "changed": "өөрчилсөн",
    "changing": "өөрчилж байна",
    "changes": "өөрчлөлтүүд",
    "format": "форматлах",
    "formatted": "форматласан",
    "formatting": "форматлаж байна",
    "convert": "хөрвүүлэх",
    "converted": "хөрвүүлсэн",
    "converting": "хөрвүүлж байна",
    "conversion": "хөрвүүлэлт",
    "conversions": "хөрвүүлэлтүүд",
    "transform": "хувиргах",
    "transformed": "хувиргасан",
    "transforming": "хувиргаж байна",
    "transformation": "хувиргалт",
    "translate": "орчуулах",
    "translated": "орчуулсан",
    "translating": "орчуулж байна",
    "translation": "орчуулга",
    "translations": "орчуулга",
    # construction-specific concepts
    "estimate": "тооцоо",
    "estimates": "тооцоонууд",
    "estimating": "тооцоолж байна",
    "estimator": "тооцоологч",
    "takeoff": "тоо хэмжээ гаргалт",
    "quantity": "тоо хэмжээ",
    "quantities": "тоо хэмжээ",
    "boq": "BOQ",
    "boqs": "BOQ-ууд",
    "wbs": "WBS",
    "ifc": "IFC",
    "rvt": "RVT",
    "dwg": "DWG",
    "dgn": "DGN",
    "pdf": "PDF",
    "csv": "CSV",
    "xml": "XML",
    "json": "JSON",
    "api": "API",
    "url": "URL",
    "ocr": "OCR",
    "ai": "AI",
    "cad": "CAD",
    "bim": "BIM",
    "mep": "MEP",
    "hvac": "HVAC",
    # specific construction phrases
    "concrete": "бетон",
    "steel": "ган",
    "rebar": "арматур",
    "reinforcement": "арматур",
    "reinforced": "армопэлсэн",
    "wall": "хана",
    "walls": "ханууд",
    "door": "хаалга",
    "doors": "хаалгууд",
    "wood": "мод",
    "brick": "тоосго",
    "bricks": "тоосгууд",
    "tile": "плита",
    "tiles": "плитүүд",
    "paint": "будаг",
    "plaster": "шавардлага",
    "insulation": "тусгаарлалт",
    "roof": "дээвэр",
    "roofs": "дээврүүд",
    "ceiling": "тааз",
    "floor": "шал",
    "floors": "шалууд",
    # rest
    "all": "бүх",
    "any": "ямар нэгэн",
    "all of": "бүгдийг",
    "either": "аль нь ч",
    "neither": "аль нь ч биш",
    "both": "хоёулаа",
    "and": "ба",
    "or": "эсвэл",
    "but": "гэхдээ",
    "however": "гэхдээ",
    "although": "хэдийгээр",
    "because": "учир нь",
    "since": "тул",
    "if": "хэрэв",
    "unless": "болохгүй бол",
    "when": "хэзээ",
    "while": "хооронд",
    "until": "хүртэл",
    "during": "явцад",
    "before": "өмнө",
    "after": "дараа",
    "via": "-аар дамжуулан",
    "per": "тутамд",
    "each": "тус бүр",
    "every": "бүх",
    "some": "зарим",
    "few": "цөөн",
    "many": "олон",
    "much": "их",
    "more": "илүү",
    "most": "ихэнх",
    "less": "бага",
    "least": "хамгийн бага",
    "few": "цөөн",
    "fewer": "цөөн",
    "fewest": "хамгийн цөөн",
    "lots": "их",
    "tons": "их",
    "no": "үгүй",
    "none": "байхгүй",
    "nothing": "юу ч байхгүй",
    "everything": "бүх зүйл",
    "anything": "ямар ч",
    "something": "ямар нэгэн",
    "anyone": "хэн ч",
    "everyone": "хүн бүр",
    "someone": "хэн нэг нь",
    "no one": "хэн ч биш",
    "nowhere": "хаана ч биш",
    "everywhere": "хаа сайгүй",
    "somewhere": "хаа нэгтээ",
    "anywhere": "хаана ч",
    # connectives
    "the": "",  # English article — removed
    "a": "",
    "an": "",
    "is": "нь",
    "are": "нь",
    "was": "байсан",
    "were": "байсан",
    "be": "байх",
    "been": "байсан",
    "being": "байх",
    "am": "байна",
    "have": "байх",
    "has": "байх",
    "had": "байсан",
    "having": "байх",
    "do": "хийх",
    "does": "хийдэг",
    "did": "хийсэн",
    "doing": "хийж байна",
    "can": "чадна",
    "cannot": "чадахгүй",
    "could": "чадах",
    "couldn't": "чадахгүй",
    "shall": "болно",
    "should": "ёстой",
    "shouldn't": "ёсгүй",
    "will": "болно",
    "won't": "болохгүй",
    "would": "болох",
    "wouldn't": "болохгүй",
    "may": "болно",
    "might": "болох",
    "must": "ёстой",
    "mustn't": "ёсгүй",
    "shall": "болно",
    # function words
    "your": "таны",
    "yours": "таных",
    "you": "та",
    "you're": "та",
    "you'll": "та",
    "you've": "та",
    "i": "би",
    "me": "намайг",
    "my": "миний",
    "mine": "минийх",
    "we": "бид",
    "us": "биднийг",
    "our": "манай",
    "ours": "манайх",
    "they": "тэд",
    "them": "тэдгээрийг",
    "their": "тэдний",
    "theirs": "тэдний",
    "he": "тэр",
    "him": "түүнийг",
    "his": "түүний",
    "she": "тэр",
    "her": "түүний",
    "it": "энэ",
    "its": "түүний",
    "itself": "өөрөө",
    "himself": "өөрөө",
    "herself": "өөрөө",
    "myself": "өөрөө",
    "yourself": "өөрөө",
    "ourselves": "өөрсдөө",
    "themselves": "өөрсдөө",
    # other commonly leaking
    "only": "зөвхөн",
    "just": "зөвхөн",
    "also": "мөн",
    "too": "бас",
    "either": "аль нь ч",
    "neither": "аль нь ч биш",
    "very": "маш",
    "really": "үнэхээр",
    "quite": "нэлээд",
    "almost": "бараг",
    "nearly": "бараг",
    "fully": "бүрэн",
    "partially": "хэсэгчлэн",
    "exactly": "яг",
    "approximately": "ойролцоогоор",
    "about": "тухай",
    "around": "тойрсон",
    "above": "дээр",
    "below": "доор",
    "under": "доор",
    "over": "дээгүүр",
    "up": "дээш",
    "down": "доош",
    "left": "зүүн",
    "right": "баруун",
    "north": "хойд",
    "south": "өмнөд",
    "east": "зүүн",
    "west": "баруун",
    "front": "урд",
    "back": "ард",
    "top": "дээд",
    "bottom": "доод",
    "side": "тал",
    "edge": "ирмэг",
    "center": "төв",
    "middle": "дунд",
    "inside": "дотор",
    "outside": "гадна",
    "in": "дотор",
    "out": "гадна",
    # remaining technical
    "browse": "үзэх",
    "browser": "хөтөч",
    "search": "хайх",
    "searched": "хайсан",
    "find": "олох",
    "found": "олсон",
    "finding": "олох",
    "lookup": "хайх",
    "discover": "нээх",
    "discovered": "нээсэн",
    "discovery": "нээлт",
    "explore": "судлах",
    "explored": "судалсан",
    "exploring": "судлаж байна",
    "explorer": "explorer",
    # AGPL etc — kept in protected
    "open": "нээх",
    "source": "эх сурвалж",
    "sources": "эх сурвалжууд",
    "code": "код",
    "codes": "кодууд",
    "coded": "кодлосон",
    "coding": "кодлож байна",
    "license": "лиценз",
    "audit": "аудит",
    "auditable": "аудит хийх боломжтой",
    "transfer": "шилжүүлэх",
    "transferred": "шилжүүлсэн",
    "transferring": "шилжүүлж байна",
    "transfers": "шилжүүлэлтүүд",
    "telemetry": "телеметр",
    "surprise": "гэнэтийн зүйл",
    "surprises": "гэнэтийн зүйлс",
    "lock": "түгжих",
    "locked": "түгжсэн",
    "locking": "түгжиж байна",
    "lockout": "түгжээ",
    "unlock": "тайлах",
    "unlocked": "тайлсан",
    "unlocking": "тайлж байна",
    "module": "модуль",
    "modules": "модулиуд",
    "modular": "модуль",
    "core": "цөм",
    "extend": "өргөтгөх",
    "extended": "өргөтгөсөн",
    "extending": "өргөтгөж байна",
    "extension": "өргөтгөл",
    "extensions": "өргөтгөлүүд",
    "plugin": "плагин",
    "plugins": "плагинууд",
    "addon": "нэмэлт",
    "addons": "нэмэлтүүд",
    "community": "хамт олон",
    "communities": "хамт олон",
    "ecosystem": "экосистем",
    "ecosystems": "экосистем",
    "marketplace": "маркетплейс",
    "marketplaces": "маркетплейсүүд",
    "store": "дэлгүүр",
    "stores": "дэлгүүрүүд",
    "stored": "хадгалсан",
    "storing": "хадгалж байна",
    "storage": "хадгалалт",
    "save": "хадгалах",
    "saved": "хадгалсан",
    "saving": "хадгалж байна",
    "fast": "хурдан",
    "faster": "илүү хурдан",
    "fastest": "хамгийн хурдан",
    "speed": "хурд",
    "speeds": "хурдан",
    "performance": "гүйцэтгэл",
    "performances": "гүйцэтгэлүүд",
    "performance": "гүйцэтгэл",
    # more
    "scratch": "хоосон",
    "anyone": "хэн ч",
    "involved": "оролцсон",
    "involving": "оролцох",
    "involvement": "оролцоо",
    "whether": "ямар нэг",
    "residential": "орон сууцны",
    "commercial": "арилжааны",
    "industrial": "үйлдвэрийн",
    "infrastructure": "дэд бүтэц",
    "infrastructures": "дэд бүтэц",
    "scale": "хэмжээ",
    "scaled": "хэмжсэн",
    "scaling": "хэмжих",
    "scope": "хүрээ",
    "house": "сууц",
    "houses": "сууцууд",
    "facility": "байгууламж",
    "facilities": "байгууламжууд",
    "platform": "платформ",
    "platforms": "платформууд",
    "system": "систем",
    "systems": "системүүд",
    "service": "үйлчилгээ",
    "services": "үйлчилгээ",
    "software": "програм хангамж",
    "hardware": "техник хангамж",
    "computer": "компьютер",
    "computers": "компьютерүүд",
    "machine": "машин",
    "machines": "машинууд",
    "machinery": "машин механизм",
    "equipment": "тоног төхөөрөмж",
    "tools": "хэрэгсэл",
    "tool": "хэрэгсэл",
    "device": "төхөөрөмж",
    "devices": "төхөөрөмжүүд",
    "phone": "утас",
    "phones": "утаснууд",
    "mobile": "мобайл",
    "tablet": "таблет",
    "desktop": "ширээний",
    "laptop": "ноутбук",
    "data": "өгөгдөл",
    "datum": "өгөгдөл",
    "info": "мэдээлэл",
    "information": "мэдээлэл",
    "knowledge": "мэдлэг",
    "wisdom": "мэргэн ухаан",
    "intelligence": "оюун ухаан",
    "expertise": "мэргэжил",
    "experience": "туршлага",
    "experiences": "туршлагууд",
    "skill": "ур чадвар",
    "skills": "ур чадварууд",
    "ability": "чадвар",
    "abilities": "чадварууд",
    "talent": "авьяас",
    "talents": "авьяасууд",
    "asset": "хөрөнгө",
    "assets": "хөрөнгөнүүд",
    "valuable": "үнэ цэнэтэй",
    "value": "үнэ цэнэ",
    "values": "үнэ цэнэнүүд",
    "worth": "үнэ",
    "worthy": "хүндлэлтэй",
    "worthless": "үнэгүй",
    "important": "чухал",
    "importance": "ач холбогдол",
    "essential": "зайлшгүй шаардлагатай",
    "essence": "мөн чанар",
    "core": "цөм",
    "central": "төв",
    "main": "гол",
    "primary": "анхдагч",
    "secondary": "хоёрдогч",
    "tertiary": "гуравдагч",
    "key": "түлхүүр",
    "keys": "түлхүүрүүд",
    "critical": "чухал",
    "vital": "амин чухал",
    "necessary": "шаардлагатай",
    "needed": "хэрэгтэй",
    "required": "шаардлагатай",
    "optional": "сонголтын",
    "preferred": "илүүд үздэг",
    "preferred": "илүүд үздэг",
    "best": "хамгийн сайн",
    "good": "сайн",
    "better": "илүү сайн",
    "great": "маш сайн",
    "excellent": "маш сайн",
    "perfect": "төгс",
    "ideal": "хамгийн зөв",
    "fine": "сайн",
    "ok": "за",
    "okay": "за",
    "right": "зөв",
    "wrong": "буруу",
    "correct": "зөв",
    "incorrect": "буруу",
    "true": "үнэн",
    "false": "худал",
    "real": "бодит",
    "fake": "хуурамч",
    "genuine": "жинхэнэ",
    "authentic": "жинхэнэ",
    "original": "анхны",
    "originals": "анхны",
    "copy": "хуулбар",
    "copies": "хуулбарууд",
    "copied": "хуулсан",
    "copying": "хуулж байна",
    "duplicate": "хуулбар",
    "duplicates": "хуулбарууд",
    "duplicated": "хуулбарласан",
    "duplicating": "хуулбарлаж байна",
    "instance": "хэрэглээ",
    "instances": "хэрэглээ",
    "example": "жишээ",
    "examples": "жишээнүүд",
    "sample": "сорьц",
    "samples": "сорьц",
    "specimen": "сорьц",
    "specimens": "сорьц",
    "case": "тохиолдол",
    "cases": "тохиолдлууд",
    "situation": "нөхцөл",
    "situations": "нөхцлүүд",
    "scenario": "хувилбар",
    "scenarios": "хувилбарууд",
    "test": "тест",
    "tests": "тестүүд",
    "testing": "тестлэлт",
    "tested": "тестлэсэн",
    "tester": "тестлэгч",
    "testers": "тестлэгчид",
    "demo": "демо",
    "demos": "демо",
    "demonstration": "үзүүлэн",
    "demonstrations": "үзүүлэн",
    "preview": "урьдчилан үзэх",
    "previews": "урьдчилсан үзэх",
    "trial": "туршилт",
    "trials": "туршилт",
    "experiment": "туршилт",
    "experiments": "туршилт",
    "research": "судалгаа",
    "researches": "судалгаанууд",
    "investigation": "судалгаа",
    "investigations": "судалгаанууд",
    "study": "судлал",
    "studies": "судлалууд",
    "analysis": "шинжилгээ",
    "analyses": "шинжилгээнүүд",
    # last but very important
    "loading": "ачаалж байна",
    "loaded": "ачаалсан",
    "load": "ачаалах",
    "fetching": "татаж байна",
    "fetched": "татсан",
    "fetch": "татах",
    "saving": "хадгалж байна",
    "saved": "хадгалсан",
    "save": "хадгалах",
    "syncing": "синхрончилж байна",
    "synced": "синхрончилсон",
    "sync": "синхрон",
    "synchronizing": "синхрончилж байна",
    "synchronized": "синхрончилсон",
    "synchronization": "синхрончлол",
    "processing": "боловсруулж байна",
    "processed": "боловсрууссан",
    "process": "боловсруулах",
    "checking": "шалгаж байна",
    "checked": "шалгасан",
    "check": "шалгах",
}

INTERP_RE = re.compile(r"\{\{[^}]+\}\}")
INTERP2_RE = re.compile(r"\{[a-zA-Z_][a-zA-Z0-9_]*\}")
HTML_RE = re.compile(r"</?[a-zA-Z][^>]*>")
NUM_RE = re.compile(r"\b\d+([.,]\d+)*\b")


def protect_special(text: str) -> tuple[str, list[str]]:
    """Replace placeholders and protected terms with sentinels."""
    tokens: list[str] = []

    def keep(m: re.Match) -> str:
        tokens.append(m.group(0))
        return f"\x00{len(tokens)-1}\x00"

    text = INTERP_RE.sub(keep, text)
    text = INTERP2_RE.sub(keep, text)
    text = HTML_RE.sub(keep, text)
    # Protected technical terms
    for term in sorted(PROTECTED, key=len, reverse=True):
        pat = re.compile(r"(?<!\w)" + re.escape(term) + r"(?!\w)")
        text = pat.sub(keep, text)
    return text, tokens


def restore(text: str, tokens: list[str]) -> str:
    def back(m: re.Match) -> str:
        idx = int(m.group(1))
        return tokens[idx] if 0 <= idx < len(tokens) else m.group(0)
    return re.sub(r"\x00(\d+)\x00", back, text)


def replace_words(text: str) -> str:
    """Replace English words case-aware."""
    def replacer(m: re.Match) -> str:
        w = m.group(0)
        lw = w.lower()
        if lw in WORDS:
            t = WORDS[lw]
            if not t:
                return ""
            # Preserve case for first letter
            if w[0].isupper() and len(w) > 0:
                return t[0].upper() + t[1:] if t else t
            return t
        return w

    return re.sub(r"\b[A-Za-z][A-Za-z']*\b", replacer, text)


def cleanup(text: str) -> str:
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\s+([.,;:!?])", r"\1", text)
    return text.strip()


def has_cyrillic(s: str) -> bool:
    return any("Ѐ" <= c <= "ӿ" for c in s)


def main() -> None:
    en_text = EN_PATH.read_text(encoding="utf-8")
    mn_text = MN_PATH.read_text(encoding="utf-8")

    pat = re.compile(r'^(\s*)"((?:[^"\\]|\\.)+)"\s*:\s*"((?:[^"\\]|\\.)*)"(,?)\s*$')

    # Build EN map
    en_full = re.compile(r'"((?:[^"\\]|\\.)+)"\s*:\s*"((?:[^"\\]|\\.)*)"')
    en_pairs = {m.group(1): m.group(2) for m in en_full.finditer(en_text)}

    out_lines: list[str] = []
    count_cleaned = 0

    for line in mn_text.splitlines(keepends=True):
        stripped = line.rstrip("\n").rstrip("\r")
        m = pat.match(stripped)
        if m:
            indent, key, value, comma = m.group(1), m.group(2), m.group(3), m.group(4)
            en_v = en_pairs.get(key, "")
            # Only operate on entries that have Cyrillic AND differ from English
            # (i.e. already-translated but possibly mixed)
            if has_cyrillic(value) and value != en_v:
                # Unescape current value for processing
                cur = value.replace('\\"', '"').replace("\\\\", "\\")
                protected, tokens = protect_special(cur)
                cleaned = replace_words(protected)
                cleaned = restore(cleaned, tokens)
                cleaned = cleanup(cleaned)
                if cleaned != cur:
                    # Re-escape
                    esc = cleaned.replace("\\", "\\\\").replace('"', '\\"')
                    new_line = f'{indent}"{key}": "{esc}"{comma}\n'
                    out_lines.append(new_line)
                    count_cleaned += 1
                    continue
        out_lines.append(line)

    MN_PATH.write_text("".join(out_lines), encoding="utf-8")
    print(f"Cleaned {count_cleaned} entries")


if __name__ == "__main__":
    main()
